### ISSUE TITLE
"The browser based authentication dialog failed to complete" 

### ISSUE THREAD

**Issue by jhaneyrf** [git-ecosystem/git-credential-manager#1025]
### Version

2.0.785+6074e4e3d3

### Operating system

Windows

### OS version or distribution

Windows Server 2016 (VMWare virtual machine?)

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}@dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

When I type "git push" from GitBash on this machine, the code that I've written locally is pushed to the remote Azure DevOps repo.

### Actual behavior

When I try to run the "git push" command, I get the error message

fatal: The browser based authentication dialog failed to complete. Reason: The server or proxy was not found.

I am then given a dialog to type in a password. But after I type in my password, the authentication still fails.

When I do this on other machines, I get taken to a little web dialog that prompts for my password and then sends a push notification to my phone for two-factor authentication.

A search on StackOverflow suggested solving the problem by setting Internet Explorer as the default browser. Unfortunately, it looks like Internet Explorer is blocked on this machine from accessing the Internet by my IT department (presumably because IE is no longer supported). I can open the Azure links just fine in Google Chrome and Microsoft Edge on this machine.

Is it possible that Git for Windows or GCM only works when you have Internet Explorer enabled? I cannot see any configuration settings that let me tell GCM or Git to use a different browser. I'm on Git for Windows version 2.38.1.windows.1, so maybe there is a newer version that has solved this problem.

I think I need to understand this problem well enough to tell my IT department how to help me fix it, and I am happy to provide you with any other details you need to help me better diagnose things.

### Logs

Log from "git push" command

17:27:51.019162 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
17:27:51.024172 git.c:460               trace: built-in: git push
17:27:51.025168 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin 'https://{org}@dev.azure.com/{...}/_git/{repo}'
17:27:51.046167 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:27:51.048177 git.c:750               trace: exec: git-remote-https origin 'https://{org}@dev.azure.com/{...}/_git/{repo}'
17:27:51.048177 run-command.c:655       trace: run_command: git-remote-https origin 'https://{org}@dev.azure.com/{...}/_git/{repo}'
17:27:51.072171 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:27:51.294977 run-command.c:655       trace: run_command: 'git credential-manager-core get'
17:27:51.375990 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:27:51.377990 git.c:750               trace: exec: git-credential-manager-core get
17:27:51.377990 run-command.c:655       trace: run_command: git-credential-manager-core get
17:27:51.487011 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.785.29792
17:27:51.493011 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
17:27:51.493011 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
17:27:51.493011 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 14393)
17:27:51.493011 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
17:27:51.493011 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: get
17:27:51.547020 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
17:27:51.564020 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
17:27:51.565020 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
17:27:51.565020 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=dev.azure.com
17:27:51.565020 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	path={...}/_git/{repo}
17:27:51.565020 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username={org}
17:27:51.704048 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
17:27:51.755052 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
17:27:51.756177 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.

17:27:51.757053 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
17:27:51.812060 ...osHostProvider.cs:85 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://dev.azure.com/{org} account=...
17:27:51.917077 ...osHostProvider.cs:90 trace: [GetCredentialAsync] No existing credentials found.
17:27:51.917077 ...osHostProvider.cs:93 trace: [GetCredentialAsync] Creating new credential...
17:27:51.918077 ...sHostProvider.cs:194 trace: [GeneratePersonalAccessTokenAsync] Determining Microsoft Authentication Authority...
17:27:51.972082 ...eDevOpsRestApi.cs:43 trace: [GetAuthorityAsync] HTTP: HEAD https://dev.azure.com/{org}
17:27:51.973085 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
17:27:52.360257 ...pClientFactory.cs:97 trace: [CreateClient] Custom certificate verification has been enabled with certificate bundle at C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
17:27:52.540288 ...eDevOpsRestApi.cs:46 trace: [GetAuthorityAsync] HTTP: Response code ignored.
17:27:52.540288 ...eDevOpsRestApi.cs:47 trace: [GetAuthorityAsync] Inspecting headers...
17:27:52.542288 ...eDevOpsRestApi.cs:54 trace: [GetAuthorityAsync] Found WWW-Authenticate header with Bearer authority 'https://login.microsoftonline.com/...'.
17:27:52.542288 ...sHostProvider.cs:196 trace: [GeneratePersonalAccessTokenAsync] Authority is 'https://login.microsoftonline.com/...'.
17:27:52.542288 ...sHostProvider.cs:199 trace: [GeneratePersonalAccessTokenAsync] Getting Azure AD access token...
17:27:52.682309 ...uthentication.cs:313 trace: [RegisterTokenCacheAsync] Configuring Microsoft Authentication token cache to instance shared with Microsoft developer tools...
17:27:52.702312 ...uthentication.cs:367 trace: [RegisterTokenCacheAsync] Microsoft developer tools token cache configured.
17:27:52.811329 ...uthentication.cs:179 trace: [GetTokenAsync] Performing interactive auth with embedded web view...
17:27:52.875340 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
17:27:53.242200 ...pClientFactory.cs:97 trace: [CreateClient] Custom certificate verification has been enabled with certificate bundle at C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
fatal: The browser based authentication dialog failed to complete. Reason: The server or proxy was not found.
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<AcquireAuthorizationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Authentication.MicrosoftAuthentication.<GetTokenAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AzureRepos.AzureReposHostProvider.<GeneratePersonalAccessTokenAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AzureRepos.AzureReposHostProvider.<GetCredentialAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Commands.GetCommand.<ExecuteInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitCredentialManager.Commands.GitCommandBase.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.CommandHandler.<GetExitCodeAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
17:27:53.740754 run-command.c:655       trace: run_command: 'C:/Program Files/Git/mingw64/bin/git-askpass.exe' 'Password for '\''https://{org}@dev.azure.com/{...}/_git/{repo}'\'': '
17:27:56.743129 run-command.c:655       trace: run_command: 'git credential-manager-core erase'
17:27:56.818142 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:27:56.820142 git.c:750               trace: exec: git-credential-manager-core erase
17:27:56.820142 run-command.c:655       trace: run_command: git-credential-manager-core erase
17:27:56.927163 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.785.29792
17:27:56.933161 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
17:27:56.933161 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
17:27:56.933161 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 14393)
17:27:56.933161 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
17:27:56.933161 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: erase
17:27:56.986172 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
17:27:57.003175 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
17:27:57.004175 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
17:27:57.004175 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=dev.azure.com
17:27:57.004175 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	path={...}/_git/{repo}
17:27:57.004175 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username={org}
17:27:57.004175 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
17:27:57.143198 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
17:27:57.196203 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
17:27:57.197202 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
17:27:57.198201 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
17:27:57.252210 ...sHostProvider.cs:150 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://dev.azure.com/{org} account=...
17:27:57.359232 ...sHostProvider.cs:157 trace: [EraseCredentialAsync] No credential was erased.
17:27:57.359232 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://dev.azure.com/{...}/_git/{repo}/'

gcm-diagnose.log

Diagnose log at 2023-01-11T23:37:56Z

Executable: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
Version: 2.0.785+6074e4e3d3

------------
Diagnostic: Environment
Skipped: False
Success: True
Exception: None
Log:
OSType: Windows
OSVersion: 10.0 (build 14393)
Reading environment variables... OK
 Variables:
HOMEPATH=\Users\...
USERNAME=...
COMPUTERNAME=PANDAS2
MSYSTEM=MINGW64
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
WINDIR=C:\Windows
ProgramData=C:\ProgramData
CONDA_PYTHON_EXE=C:/ProgramData/Anaconda3/python.exe
CONDA_DEFAULT_ENV=base
GCM_TRACE=1
CONFIG_SITE=C:/Program Files/Git/etc/config.site
LC_CTYPE=en_US.UTF-8
USERDOMAIN={domain}
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
MSYSTEM_PREFIX=C:/Program Files/Git/mingw64
MINGW_PREFIX=C:/Program Files/Git/mingw64
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program Files\Git\usr\share\aclocal
TEMP=C:\Users\...
LOCALAPPDATA=C:\Users\...
MANPATH=C:\Program Files\Git\mingw64\local\man;C:\Program Files\Git\mingw64\share\man;C:\Program Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program Files\Git\usr\man;C:\Program Files\Git\share\man
_CE_CONDA=
SESSIONNAME=RDP-Tcp#36
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
MSYSTEM_CARCH=x86_64
PROGRAMFILES=C:\Program Files (x86)
CLIENTNAME=...
_CE_M=
USERDNSDOMAIN={domain}
TERM_PROGRAM_VERSION=3.6.1
CONDA_SHLVL=1
PROCESSOR_REVISION=5504
SYSTEMROOT=C:\Windows
TERM_PROGRAM=mintty
PROCESSOR_LEVEL=6
NUMBER_OF_PROCESSORS=18
SSH_ASKPASS=C:/Program Files/Git/mingw64/bin/git-askpass.exe
SHLVL=1
APPDATA=C:\Users\...
SYSTEMDRIVE=C:
ORIGINAL_TMP=C:/Users/...
CONDA_EXE=C:/ProgramData/Anaconda3/Scripts/conda.exe
PUBLIC=C:\Users\Public
FPS_BROWSER_USER_PROFILE_STRING=Default
PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program Files\Git\mingw64\share\pkgconfig
MSYSTEM_CHOST=x86_64-w64-mingw32
ORIGINAL_TEMP=C:/Users/...
TERM=xterm
PAGER=less
PLINK_PROTOCOL=ssh
INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program Files\Git\share\info
ProgramW6432=C:\Program Files
PATH=C:/Program Files/Git/mingw64/libexec/git-core;C:\ProgramData\Anaconda3\;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts\;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\Scripts\condabin;C:\Users\{user}\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\{user}\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\{user}\AppData\Local\Microsoft\WindowsApps;C:\Users\{user}\AppData\Local\GitHubDesktop\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
MINGW_CHOST=x86_64-w64-mingw32
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
GIT_TRACE=1
CONDA_PROMPT_MODIFIER=(base) 
TMPDIR=C:\Users\{user}\AppData\Local\Temp\6
TMP=C:\Users\{user}\AppData\Local\Temp\6
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
SHELL=C:\Program Files\Git\usr\bin\bash.exe
HOME=C:\Users\{user}
COMSPEC=C:\Windows\system32\cmd.exe
LOGONSERVER=\\{...}
USERPROFILE=C:\Users\{user}
DISPLAY=needs-to-be-defined
COMMONPROGRAMFILES=C:\Program Files (x86)\Common Files
CONDA_PREFIX=C:\ProgramData\Anaconda3
_=C:/Program Files/Git/mingw64/bin/git
USERDOMAIN_ROAMINGPROFILE={domain}
CommonProgramW6432=C:\Program Files\Common Files
HOMEDRIVE=C:
OLDPWD=C:/Users/{user}
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
STTASKFOLDERPATH=\Ivanti\Security Controls\Deployments
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PWD=C:/Users/{user}/Documents/repos/{repo}
EXEPATH=C:\Program Files\Git
HOSTNAME=pandas2
PROCESSOR_ARCHITEW6432=AMD64
ORIGINAL_PATH=C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\{user}\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\{user}\AppData\Local\Microsoft\WindowsApps;C:\Users\{user}\AppData\Local\GitHubDesktop\bin
PROCESSOR_ARCHITECTURE=x86
PS1=(base) \[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$ 
OS=Windows_NT
ProgramFiles(x86)=C:\Program Files (x86)
ALLUSERSPROFILE=C:\ProgramData

------------
Diagnostic: File system
Skipped: False
Success: True
Exception: None
Log:
Temporary directory is 'C:\Users\{user}\AppData\Local\Temp\6\'...
Checking basic file I/O...
Writing to temporary file 'C:\Users\{user}\AppData\Local\Temp\6\85a9446086e857749a5747e1'... OK
Reading from temporary file 'C:\Users\{user}\AppData\Local\Temp\6\85a9446086e857749a5747e1'... OK
Deleting temporary file 'C:\Users\{user}\AppData\Local\Temp\6\85a9446086e857749a5747e1'... OK
Testing IFileSystem instance...
UserHomePath: C:\Users\{user}
UserDataDirectoryPath: C:\Users\{user}\.gcm
GetCurrentDirectory(): C:\Users\{user}\Documents\repos\{repo}

------------
Diagnostic: Networking
Skipped: False
Success: True
Exception: None
Log:
Checking basic networking and HTTP stack...
Creating HTTP client... OK
IsNetworkAvailable: True
Sending HEAD request to http://example.com... OK
Sending HEAD request to https://example.com... OK
Acquiring free TCP port... OK
Testing local HTTP loopback connections...
Creating new HTTP listener for http://localhost:64904/... OK
Waiting for loopback connection... OK
Writing response... OK
Waiting for response data... OK
Loopback connection data OK
Testing with IHttpClientFactory created HTTP client...
Creating HTTP client... OK
IsNetworkAvailable: True
Sending HEAD request to http://example.com... OK
Sending HEAD request to https://example.com... OK
Acquiring free TCP port... OK
Testing local HTTP loopback connections...
Creating new HTTP listener for http://localhost:64906/... OK
Waiting for loopback connection... OK
Writing response... OK
Waiting for response data... OK
Loopback connection data OK

------------
Diagnostic: Git
Skipped: False
Success: True
Exception: None
Log:
Getting Git version... OK
Git version is '2.38.1.windows.1'
Locating current repository... OK
Git repository at 'C:/Users/{user}/Documents/repos/{repo}/.git'
Listing all Git configuration... OK
Git configuration:
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/{user}/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/{user}/.gitconfig	filter.lfs.required=true
file:C:/Users/{user}/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/{user}/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/{user}/.gitconfig	user.name={Name}
file:C:/Users/{user}/.gitconfig	user.email={email}
file:C:/Users/{user}/.gitconfig	init.defaultbranch=main
file:C:/Users/{user}/.gitconfig	http.sslverify=true
file:C:/Users/{user}/.gitconfig	gui.recentrepo=C:/Users/{user}/Documents/repos/{repo}
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://{org}@dev.azure.com/{org}/{...}/_git/{repo}
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
file:.git/config	gui.wmstate=normal
file:.git/config	gui.geometry=1322x693+38+38 254 315

------------
Diagnostic: Credential storage
Skipped: False
Success: True
Exception: None
Log:
ICredentialStore instance is of type: CredentialStore
Writing test credential... OK
Reading test credential... OK
Deleting test credential... OK

------------
Diagnostic: Microsoft authentication (AAD/MSA)
Skipped: False
Success: True
Exception: None
Log:
Broker not supported.
Flow type is: Auto
Gathering MSAL token cache data... OK
CacheDirectory: C:\Users\{user}\AppData\Local\.IdentityService
CacheFileName: msal.cache
CacheFilePath: C:\Users\{user}\AppData\Local\.IdentityService\msal.cache
Creating cache helper... OK
Verifying MSAL token cache persistence... OK

------------
Diagnostic: GitHub API
Skipped: False
Success: True
Exception: None
Log:
Using 'https://github.com/' as API target.
Querying '/meta' endpoint... OK

**Comment by jhaneyrf** [comment]
I also want to add that when I type "git config --help" it automatically opens a window in whichever web browser I have set to be my default. So the hard dependency on Internet Explorer seems to be only true for "git push" and "git pull" actions.

**Comment by ldennington** [comment]
We believe this to be an issue with the embedded Microsoft Authentication window on a Windows server machine. Can you try using the system browser by setting the below config and seeing if it resolves the issue?

`git config --global credential.msauthflow system`

**Comment by ldennington** [comment]
Closing - lack of response, and above setting should resolve this problem.

**Comment by bkrrk** [comment]
> git config --global credential.msauthflow system

I faced it today, and this recommendation worked, fixed the problem. Thank you
