### ISSUE TITLE
Could our version of TFS be too old to work with GCM authentication?

### ISSUE THREAD

**Issue by Rod-in-NM** [git-ecosystem/git-credential-manager#1026]
### Version

2.0.877+c7c35983b8

### Operating system

Windows

### OS version or distribution

Windows 10 Enterprise, x64

### Git hosting provider(s)

Other - please describe below

### Other hosting provider

on-prem TFS 2015

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

When issuing simple Git commands, such as `git pull` to perform that command

### Actual behavior

When I try to issue simple Git commands like `git pull` I get the following warning message:

> warning: auto-detection of host provider took too long (>2000ms)
> warning: see https://aka.ms/gcm/autodetect for more information
> Already up to date

I went to the URL, which brought me here. The sections on "Self-hosted/on-prem detection" and the manual configuration addresses what must be done, but I've got two issues with them. First, the example given is to globally configure the `credential.provider`. I don't want to do that, as I'm using multiple providers. Secondly, I don't know what the syntax is for configuring `credential.provider` so that I can set it on a repo-by-repo basis and what the syntax is for specifying the URL and how I'd reference our TFS 2015 instance.

Additionally, I'm wondering of our TFS 2015 is too old and won't work well with GCM? I am confused by that last "Already up to date" message, after getting the warning message.

**Comment by ldennington** [comment]
This should make the warning go away:

`git config --global credential.[hostname].provider generic`

Hostname will be the hostname of your TFS server. There shouldn't be an issue with setting this in your global config.

**Comment by Rod-in-NM** [comment]
So, @ldennington, if I set the credential.provider to our local TFS server, then what happens when I try to use either GitHub or Azure DevOps Services? Perhaps it's just me, not understanding how GCM is supposed to work.

**Comment by ldennington** [comment]
No worries @Rod-in-NM. Basically, you're setting the provider for a specific hostname. Here's an example from [the docs](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialprovider):

`git config --global credential.ghe.contoso.com.provider github`

The example is saying _use github specifically for this hostname_. So, as long as your GitHub/Azure DevOps Services/etc. repos have different hostnames than the TFS repo (which I believe should be the case), you will be able to set this and still have the appropriate behavior for those providers.

**Comment by ldennington** [comment]
Closing due to lack of response. If this is still an issue, please feel free to re-open.
