### ISSUE TITLE
Installation failure on Mac OS Ventura 13.1

### ISSUE THREAD

**Issue by deniscooper** [git-ecosystem/git-credential-manager#1035]
When trying to install both through home-brew and the downloaded package I encounter an installation error with a general error message. 

Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=xxx USER=xxx USERNAME=xx /usr/sbin/installer -pkg /usr/local/Caskroom/git-credential-manager-core/2.0.886/gcm-osx-x64-2.0.886.pkg -target / -allowUntrusted` exited with 1. Here's the output:
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.886.pkg”.)

**Comment by EricL0wry** [comment]
Similar issue here, same failure message with the exception of the package being "gcm-osx-arm64-2.0.886.pkg". Using MacBook Pro with M1 Pro, Ventura 13.1. Install fails both via Homebrew and when downloading the .pkg file directly from Github.

**Comment by ldennington** [comment]
Can you run the `.pkg` again, this time (before hitting continue), can you use the following command to look at the installer log for more detailed messages (including errors):

`cmd-L “Detail Level -> Show All Logs”`

**Comment by mickut** [comment]
Ran into same issue. I noticed swift was broken after update to Ventura. I launched xcode, which then (re)installed the dev-tools for current OS version and fixed swift at the same time. After that the installation of GCM worked.

**Comment by richardscholten73** [comment]
I had the same problem.
In the install log:
```shell
...
Feb  3 10:01:19 Richards-MacBook-Pro package_script_service[45113]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.8fATKp/Scripts/com.microsoft.gitcredentialmanager.dYZVzZ
Feb  3 10:01:21 Richards-MacBook-Pro package_script_service[45113]: ./postinstall: Configuring component 'Git Credential Manager'...
Feb  3 10:01:21 Richards-MacBook-Pro package_script_service[45113]: ./postinstall: fatal: Failed to unset all Git configuration multi-valued entries 'credential.helper' [1]
Feb  3 10:01:21 Richards-MacBook-Pro package_script_service[45113]: ./postinstall: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
...
```

Seems like the devs asummed you have Xcode installed, or at least the Xcode command line tools.
You can trigger the install of the commandline tools with:
```
xcode-select --install
```

![image](https://user-images.githubusercontent.com/15611191/216564499-18b908b5-cecf-49f7-9c85-19328e8a2840.png)

https://www.freecodecamp.org/news/install-xcode-command-line-tools/#:~:text=Developers%20need%20to%20install%20Xcode,install%20the%20full%20Xcode%20application.

After installing the command line tools, the instalation finished without error.

maybe the devs can add the prompt for installing the commandline tools?

**Comment by ldennington** [comment]
GCM requires a Git installation to work on macOS. The default Apple Git installation comes bundled with the XCode `CommandlineTools` package. You have to install this package to be able to use Apple Git (which is run as part of GCM's install).

Alternatively, you can install Homebrew Git using the command `brew install git` (just make sure you install Homebrew first as well).

**Comment by tlaak** [comment]
For any lost souls out there: I got the same error when both 1) installing with Homebrew and 2) running the pkg installer. The installer log (press CMD+L and select "Show all logs") revealed that my .gitconfig file wasn't writable (I don't know why) and it failed the installation. After fixing the permissions it worked just fine.
