### ISSUE TITLE
Integrate with Git's `TRACE2` tracing system

### ISSUE THREAD

**Issue by ldennington** [git-ecosystem/git-credential-manager#1101]
Implement `TRACE2` tracing with the goals of:

1. Integrating more closely with Git's [main tracing system](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt).
2. Obtaining better insight into GCM usage/issues (for users who set specific environment variables/config values).

At a high level, this effort will involve outputting 3 different types of trace information triggered by setting 3 different environment variables/configurations:

1. ["Normal format target" `TRACE2` tracing](https://git-scm.com/docs/api-trace2#_the_normal_format_target): this will involve writing lines of human-readable trace information to stderr/user-specified output files.
5. ["Event format target" `TRACE2` tracing](https://git-scm.com/docs/api-trace2#_the_normal_format_target): this will involve writing json-formatted trace information to stderr/user-specified output files.
6. ["Performance format target" `TRACE2` tracing](https://git-scm.com/docs/api-trace2#_the_normal_format_target): this will involve writing specially-formatted trace information for assessing application performance to stderr/user-specified output files.

The following events will initially be tracked by the aforementioned format targets (with the potential to add additional events in the future):

1. [Version](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codeversioncode)
2. [Start](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codestartcode)
3. [Exit](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codeexitcode)
7. [Error](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codeerrorcode)
8. [ChildStart](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codechildstartcode)
9. [ChildExit](https://git-scm.com/docs/api-trace2#Documentation/technical/api-trace2.txt-codechildexitcode)

**Comment by mjcheetham** [comment]
Completed!
