### ISSUE TITLE
Cannot be installed in Ubuntu-22.04

### ISSUE THREAD

**Issue by escherstair** [git-ecosystem/git-credential-manager#1107]
If I try to install `gcm-linux_amd64.2.0.886.deb` in my Ubuntu 22.04 I get the following error
```
Reading database ... 220974 files and directories currently installed.)
Preparing to unpack gcm-linux_amd64.2.0.886.deb ...
Unpacking gcm (2.0.886) ...
dpkg: error processing archive gcm-linux_amd64.2.0.886.deb (--install):
 trying to overwrite '/usr/local/share/gcm-core/Atlassian.Bitbucket.UI', which is also in package gcmcore 2.0.696
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 gcm-linux_amd64.2.0.886.deb
```

**Comment by ldennington** [comment]
This does seem like a problem. While we work on triaging it, can you try the workaround of uninstalling your current package and then re-attemping the install of the new one? You can find uninstall instructions [here](url).

**Comment by escherstair** [comment]
Hello @ldennington 
the link you posted pointed to an empty list of issues.
Can you fix, please?

**Comment by ldennington** [comment]
@escherstair - sorry for the incorrect link! [Here is the correct one](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/install.md#uninstall-2). Given that the versions still aren't matching, can you follow those instructions to uninstall/reinstall and see if the versions align after that?

**Comment by ldennington** [comment]
Closing due to lack of response.
