### ISSUE TITLE
.deb package for Linux ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by jlanssie** [git-ecosystem/git-credential-manager#1117]
### Feature description

Please provide a .deb package for Linux ARM (Raspberry Pi). 

Compiling from source code seems to throw issues (at least on my machine) for Raspberry Pis running Ubuntu Server.

**Comment by ldennington** [comment]
Have you tried the [ .NET tool approach](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/install.md#net-tool)? I don't have a Raspberry Pi, but I've spoken with others who have successfully installed with that method.

**Comment by jlanssie** [comment]
I tried the .net tool and building source but neither worked for me.

**Comment by ldennington** [comment]
What model of Raspberry Pi are you using? What is your Ubuntu Server version?

**Comment by jlanssie** [comment]
Raspberry Pi 4 - Ubuntu Server 22.04

**Comment by ldennington** [comment]
And what's the error you're seeing when you try to install as a .NET tool?

**Comment by ldennington** [comment]
Also, can you please provide the information requested in the [issue template](https://github.com/git-ecosystem/git-credential-manager/issues/new?assignees=&labels=auth-issue&template=auth-issue.yml)? That will help us better diagnose what is happening.

**Comment by haukex** [comment]
I agree that a `.deb` package would be really nice. But I was able to get git-credential-manager installed on a Raspberry Pi 4 with 64-bit Raspbian with the following steps:

Download the latest .NET 6.0 SDK for Arm64 from <https://dotnet.microsoft.com/en-us/download/dotnet/6.0>

```
mkdir -vp $HOME/.dotnet
tar zxvf dotnet-sdk-6.*-linux-arm64.tar.gz -C $HOME/.dotnet
echo 'export DOTNET_ROOT=$HOME/.dotnet' >>~/.profile
echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >>~/.profile
echo 'export DOTNET_CLI_TELEMETRY_OPTOUT=1' >>~/.profile
# log out and in again for .profile changes to take effect
dotnet tool install -g git-credential-manager
```

**Comment by ldennington** [comment]
Closing in favor of #606 - we will start publishing an ARM package on completion of that issue.
