### ISSUE TITLE
When working with BitBucket credentials are never reused

### ISSUE THREAD

**Issue by TorRanfelt** [git-ecosystem/git-credential-manager#1119]
### Version

2.0.886+ea93cb5158

### Operating system

Windows

### OS version or distribution

Windows 10

### Git hosting provider(s)

Bitbucket Cloud

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Not having to resupply credentials on each pull/push.

### Actual behavior

On one of our computers we had problems with pulling from BitBucket. That has been fixed, but now the App-password must be entered each time a pull or push is made.
We have tried uninstalling Git for Windows (which includes git-credential-manager). Also deleting "[...]\Program Files\git" and deleting .git files in the user directory and removing BitBucket credentials under windows-credentials. In other words allowing for a completely fresh install.

We then install the latest version of Git for Windows (2.39.2).
We try to do a pull, and there are two options. By browser or by password. By browser sends the user to a page where you have to grant access, but that just leads one to an URL at localhost which doesn't work. Hence we use the password option instead. Username and App-password is entered and the pull works. However, during the next pull the credentials have to be supplied again. Under windows-credentials there are now credentials for BitBucket, but apparently they are not used.

I did see the closed issue https://github.com/GitCredentialManager/git-credential-manager/issues/1116 but running "git config --global credential.helper wincred" did not help.

**Comment by ldennington** [comment]
Can you please provide the results of running `git credential-manager diagnose`?

**Comment by TorRanfelt** [comment]
$ git credential-manager diagnose
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
 [ OK ] Networking
 [ OK ] Git
 [ OK ] Credential storage
 [ OK ] Microsoft authentication (AAD/MSA)
 [ OK ] GitHub API

Diagnostic summary: 7 passed, 0 skipped, 0 failed.

Do you need the log file too? I ask because I would need to redact content then.

**Comment by ldennington** [comment]
Yes, please include the logs.

**Comment by TorRanfelt** [comment]
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/10957021/gcm-diagnose.log)

**Comment by TorRanfelt** [comment]
We have the problem on two computers, and hence I don't dare updating git or changing credentials/app-password on any other computer.

**Comment by gautaz** [comment]
Hello, same issue here.

I was wondering why none of my colleagues are using Git for Windows.
When asking them, I always got the same answer: "doesn't work" (with no particular explanation).

So I just operated a fresh Windows 10 VM + Git for Windows 2.40.0 install and the behavior sticks to what @TorRanfelt describes (Windows is not my main OS hence the VM).

@ldennington Did you manage to reproduce the issue?
Is there anything else we can do to help with the issue diagnosis ?

**Comment by ldennington** [comment]
I investigated this morning and was able to repro the issue. This is what fixed it for me:

1. I set my `bitBucketAuthModes` config to basic using [these instructions](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/configuration.md#credentialbitbucketauthmodes).
2. I ensured my App Password had account scopes, as well as some minimal workspace, project, and repository scopes as shown here:
![Screenshot 2023-04-20 at 11 35 38 AM](https://user-images.githubusercontent.com/11321782/233444466-00e2f6d1-3b2a-49e3-86cd-f25cc50a1595.png).
  Note that your scopes may be different based on your unique requirements.

**Comment by gautaz** [comment]
Hello @ldennington, adding the "read" account permissions solved the issue, at least for me :-).
So for git client purposes, I only need repositories read/write and accound read permissions.

Thanks a lot for your answer and your time.

I was wondering if this requirement could appear as a warning note on the project's README when using bitbucket?

**Comment by ldennington** [comment]
I'm not sure there's a place in the `README` where this information would fit. Instead, I [opened a PR](https://github.com/git-ecosystem/git-credential-manager/pull/1213) with some notes in the `bitbucket-development.md` document.

And @TorRanfelt you're right, forcing `basic` auth was overkill on my part - the real solution is adding the correct permissions to the App Password, so that's the only thing I call out in my updates to the docs.
