### ISSUE TITLE
Running `git-credential-manager.exe` from WSL2 on Windows 10 takes too long to execute

### ISSUE THREAD

**Issue by felipecrs** [git-ecosystem/git-credential-manager#1134]
```console
$ wsl.exe --version
wsl.exe --version
Versão do WSL: 1.0.3.0
Versão do kernel: 5.15.79.1
Versão do WSLg: 1.0.47
Versão do MSRDC: 1.2.3575
Versão do Direct3D: 1.606.4
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows versão: 10.0.19044.2604

$ export GIT_EXEC_PATH="$(git --exec-path)"
$ export WSLENV="${WSLENV}:GIT_EXEC_PATH/wp"
$ /usr/local/share/gcm/git-credential-manager.exe --version
<takes 3 minutes>
```

The same issue does NOT occur in Windows 11.

```console
$ wsl.exe --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1343

$ export GIT_EXEC_PATH="$(git --exec-path)"
$ export WSLENV="${WSLENV}:GIT_EXEC_PATH/wp"
$ /usr/local/share/gcm/git-credential-manager.exe --version
<takes 3 seconds>
```

I'm using 2.0.931. 

I don't understand what's going on, but this is slowing down my git commands by a lot unfortunately. I'm happy to provide more information if needed.

**Comment by felipecrs** [comment]
PS: other commands that uses WSL interoperability does not hang like GCM. Example: powershell.exe.

**Comment by ldennington** [comment]
1. We published a [pre-release](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.935) today that contains a couple hotfixes to 2.0.931. Can you try installing it to see if it resolves the issue?
2. How are you installing GCM? Admittedly, I don't use WSL that often, but I tried installing GCM 2.0.931 on my Windows machine, then ran the `--version` command using the path `"/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe"` from WSL and it worked as expected. I also downloaded and installed the Debian package for 2.0.931 in WSL then ran `git-credential-manager --version`, which also worked as expected.

**Comment by felipecrs** [comment]
1. I will let you know later, unfortunately this issue only happens in my colleagues' workstation as they use W10 (where I use W11).
2. I extract the https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.931/gcm-win-x86-2.0.931.zip into some folder like `/usr/local/share/gcm`, then `sudo chmod +x /usr/local/share/gcm/git-credential-manager.exe` and execute it from there with the environment variables set as in the initial example.

Is there any way I can enable some debug logs so I could hopefully see at which part of the code GCM is hanging?

**Comment by ldennington** [comment]
Yes - running the following should write useful traces to `~/gcm.trace` and `~/git.trace` files for us:

`WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=~/gcm.trace GIT_TRACE=~/git.trace git-credential-manager
 --version`

Or, if it's easier, you can log to stderr instead of the files:

`WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git-credential-manager
 --version`

**Comment by mrbernardi** [comment]
Hey @ldennington, I'm helping Felipe to test this. Here's the outcome:

```console
$ export GIT_EXEC_PATH="$(git --exec-path)"
$ export WSLENV="${WSLENV}:GIT_EXEC_PATH/wp"
$ /usr/local/share/gcm/git-credential-manager.exe --version
<took 4min 17s before the output>
2.0.935+8b4735fc7b

$ WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 /usr/local/share/gcm/git-credential-manager.exe --version
<took 3min 35s before the fist log>
15:43:09.407896 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.935.18315
15:43:09.411899 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
15:43:09.411899 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
15:43:09.411899 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 19044)
15:43:09.411899 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: \\wsl.localhost\Ubuntu\usr\local\share\gcm\git-credential-manager
15:43:09.411899 ...\Application.cs:100  trace: [RunInternalAsync] InstallDir: \\wsl.localhost\Ubuntu\usr\local\share\gcm\
15:43:09.411899 ...\Application.cs:101  trace: [RunInternalAsync] Arguments: --version
2.0.935+8b4735fc7b
```

Neither the newer version of the logs seems to help unfortunately.

**Comment by mjcheetham** [comment]
Hmm.. looks like we're not being started until several minutes in. I think I may know what's happening here.

Because you have the (Windows) GCM executables on the Linux file system (`/usr/local/share`), whenever they are executed they must be accessed via the `//wsl/` network path. No doubt that the .NET Framework CLR is taking a long time to start because all of the required application DLLs are also being loaded over the, comparatively slow, network path.

Can you try moving the Windows GCM executables to somewhere on the Windows NTFS file system, and then reference that path inside of WSL? `/mnt/c/...`

**Comment by felipecrs** [comment]
Sure, will try that. Thanks.

**Comment by felipecrs** [comment]
By the way, another idea which I had was maybe the company's antivirus messing with it.

**Comment by ldennington** [comment]
@felipecrs - did you manage to get around to trying this to see if Matthew's solution helps? And you're correct, excessive antivirus scanning could also result in this issue.

**Comment by felipecrs** [comment]
Sorry not reporting back! Will check again.

**Comment by felipecrs** [comment]
I'll close this issue for now and reopen as soon as I manage to test it. Thanks for the support so far.

**Comment by ldennington** [comment]
@felipecrs - I see you re-opened the issue. Do you have new findings to report?

**Comment by felipecrs** [comment]
Oh wow, I thought I had reported, but it seems that I wrote the answer in some session and forgot to click in "Comment".

So, we did the test, and the outcome was that it takes 9 seconds to execute when called from within WSL2 but from a path outside WSL2 (e.g. /mnt/c/git-credential-manager.exe), and 3-4 minutes to execute when called from within WSL2 but from a path inside WSL2 (e.g. /tmp/git-credential-manager.exe).

That's interesting... but I don't know what it means exactly or what can be done to improve it.

Maybe this issue isn't caused by GCM itself, and I would appreciate if there is any suggestion on how I can iron out this possibility.

**Comment by hluengas** [comment]
I have a similar issue.

I followed the instructions [here](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/wsl.md) to configure WSL2 to use the windows executable for GCM.

(I did not install full Git for windows, just standalone GCM as I only use git in the Linux filesystem)

git is configured to use "/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe" as the credential helper.

Remote git operations now always take 10+ seconds, but do succeed.

**time git fetch**
> ________________________________________________________
> Executed in   11.07 secs      fish           external
>    usr time   34.47 millis  184.00 micros   34.28 millis
>    sys time    0.31 millis  314.00 micros    0.00 millis

**git-credential-manager --version**
> 2.0.935+8b4735fc7b

**/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe**
> Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
>    at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
>    at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
>    at GitCredentialManager.CommandContext..ctor(String[] argv)
>    at GitCredentialManager.Program.Main(String[] args)

**Comment by christianfosli** [comment]
I also experience slow (seconds, not minutes) remote git operations on WSL when using windows' git-credential-manager.exe as the credential helper, but using GCM on native linux it feels instant.

The docker team recently fixed an issue which sounds similar to me, https://github.com/docker/for-win/issues/10247, where it turned out to be antivirus software on the windows side causing slowness only when invoked from WSL due to a code signing issue.

This might be completely unrelated, but I thought I'd comment just in case.

**Comment by ldennington** [comment]
Closing stale issue - problem is due to Windows/WSL file interop and a potential antivirus slowdown.
