### ISSUE TITLE
can't use  generic login to gitee.com   

### ISSUE THREAD

**Issue by maikebing** [git-ecosystem/git-credential-manager#1144]
```
[credential "https://gitee.com"]
	provider = generic
	oauthClientId = b5da229f85d94f5d728c43e429c69527fe2dcc387d4ffcb677b91c93983adaa3
	oauthClientSecret = a9f88c722f66e54184204efa0f49b960f2666947e0b14bd0d73a8c9c1c33c340
	oauthRedirectUri = http://127.0.0.1:53119
	oauthAuthorizeEndpoint = /oauth/authorize
	oauthTokenEndpoint = /oauth/token
	oauthScopes = projects 
```
1.step 
git.exe pull -v --progress "origin"
remote: [session-58458295] The token username invalid
fatal: unable to access 'https://gitee.com/uixe/mdai.git/': The requested URL returned error: 403

2.step:

git.exe pull -v --progress "origin"
fatal: invalid_grant: 授权方式无效，或者登录回调地址无效、过期或已被撤销 //The authorization method is invalid, or the login callback address is invalid, expired, or has been revoked
error: unable to read askpass response from 'C:\Program Files\TortoiseGit\bin\SshAskPass.exe'
bash: line 1: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://gitee.com': No such file or directory

**Comment by mjcheetham** [comment]
> remote: [session-58458295] The token username invalid
> fatal: unable to access 'https://gitee.com/uixe/mdai.git/': The requested URL returned error: 403

Hello! Without knowing the details of gitee's OAuth implementation in depth, it appears from this error message that you may need to set a specific username:

https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/generic-oauth.md#token-user-name

> If your Git host requires that you specify a username to use with OAuth tokens you can either include the username in the Git remote URL, or specify a default option via Git configuration.
>
> Example Git remote with username: https://username@example.com/repo.git. In order to use special characters you need to URL encode the values; for example @ becomes %40.
>
> By default GCM uses the value OAUTH-USER unless specified in the remote URL, or overriden using the credential.<HOST>.oauthDefaultUserName configuration.

Could you try adding your gitee username either in the remote URL or setting the `credential.gitee.com.oauthDefaultUserName` config?
