### ISSUE TITLE
fatal: unable to access 'https://dev.azure.com/****/': Recv failure: Connection was reset

### ISSUE THREAD

**Issue by Shmirre** [git-ecosystem/git-credential-manager#1150]
### Version

2.0.886+ea93cb5158

### Operating system

Windows

### OS version or distribution

Windows 11

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}@dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I am authenticated in the browser and I want to clone the repository to my local device. This device doesn't have any firewall rules etc set and is a laptop for private use so it should not block any incoming requests.

I simply want to clone the Repository and start pushing code to the Azure Devops server.

### Actual behavior

I am logged in succesfully into the Azure Devops of the organization via my account.

Cloning the repository via VSCODE:
![image](https://user-images.githubusercontent.com/44161789/224956858-85d2ade6-2fd7-415c-b56f-64ec141768b6.png)

Cloning the Repo via GIT CMD:
![image](https://user-images.githubusercontent.com/44161789/224956060-555806a0-983f-48ee-bdd6-304eb37728dc.png)

Things i've tried:

- Resetting my password - Unsuccesfull
- Removing the GIT Credentials in Windows Credential Manager - This allows me to re-enter my password (which is the same as the one used to log into the azure devops) and to SUCCESFULLY CLONE / PUSH only once, afterwards it fails again.
- Just spamming the 'push' and 'sync changes' buttong in vscode makes it work 1 out of 30 times miraculously.

Sometimes if i remove my GIT credentials on my local device, i am prompted to add a password again (VSCODE & GIT both prompt me), after providing my password and my 2-Factor Authenticator , i get a 'unable to access' issue and a fatal error.

Please note that for 1,5 weeks, there was no issue in pushing and cloning repo's and all of a sudden one day after arriving at home, this error occured.

### Logs

**Log (dedacted)**
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/10966712/gcm-diagnose.log)
 

Kindly let me know if you require more information or verbose diagnostics.

**Comment by Shmirre** [comment]
Small update: Cloning the repository from devops while using the 'Clone in VSCode' button works if i use the 'Generate GIT Credentials' button. Although my git credential.manager diagnose command stil provides me with the same output of username and password as said before.

Thanks!

**Comment by ldennington** [comment]
Can you set `GIT_TRACE=1`, `GIT_TRACE_CURL=1`, `GCM_TRACE=1` and try and reproduce the problem then attach the output (redacting if needed)?

**Comment by ldennington** [comment]
Closing due to lack of response.

**Comment by joshkoppang** [comment]
Since the original poster did not respond but this page comes up in search results, I will add some context. Experiencing the same problem with the below output from `GIT_TRACE` and `GIT_TRACE_CURL`.  Note that `git push -4` succeeds when `git push` fails.

```
git push
16:32:29.362588 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
16:32:29.367862 git.c:439               trace: built-in: git push
16:32:29.367862 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://ORG@dev.azure.com/ORG/REPO/_git/REPO
16:32:29.376396 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:32:29.377438 git.c:725               trace: exec: git-remote-https origin https://ORG@dev.azure.com/ORG/REPO/_git/REPO
16:32:29.377438 run-command.c:655       trace: run_command: git-remote-https origin https://ORG@dev.azure.com/ORG/REPO/_git/REPO
16:32:29.386941 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:32:29.392522 http.c:724              == Info: Couldn't find host dev.azure.com in the (nil) file; using defaults
16:32:29.406159 http.c:724              == Info:   Trying [2620:1ec:21::20]:443...
16:32:29.434420 http.c:724              == Info: Connected to dev.azure.com (2620:1ec:21::20) port 443 (#0)
16:32:29.435424 http.c:724              == Info: ALPN: offers h2,http/1.1
16:32:29.435424 http.c:724              == Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
16:32:29.440986 http.c:724              == Info:  CAfile: C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
16:32:29.440986 http.c:724              == Info:  CApath: none
16:32:29.446986 http.c:724              == Info: Recv failure: Connection was reset
16:32:29.446986 http.c:724              == Info: OpenSSL SSL_connect: Connection was reset in connection to dev.azure.com:443
16:32:29.446986 http.c:724              == Info: Closing connection 0
16:32:29.446986 http.c:724              == Info: Recv failure: Connection was reset
fatal: unable to access 'https://dev.azure.com/ORG/REPO/_git/REPO/': Recv failure: Connection was reset
```

**Comment by jkostovich** [comment]
Hello I am experiencing the same as above. with the same error codes. This worked a few days ago, but now it fails in the same exact ways as the original poster mentioned.

**Comment by jkostovich** [comment]
I performed some further troubleshooting on this and completely bypassed GCM and still ran into the same issues. I'm leaning towards this being an Issue with Windows 11.

**Comment by purple-lemon** [comment]
Same here. Experience only in Win11 and only with Azure repositories. It's happen from time to time

**Comment by purple-lemon** [comment]
Btw I found that its not failing all requests. You may try same git command multiple times and at some point it will work. Can't say at all what affects it

**Comment by joshkoppang** [comment]
Noticed throughout the day today that the actual website (https://dev.azure.com/) experiences connection resets in Edge as well.

**Comment by ldennington** [comment]
Thanks for the thorough investigation - I think it's safe to say this is not a GCM issue at this point. If further assistance is required, it would be a good idea to reach out to [Azure DevOps support](https://azure.microsoft.com/en-us/support/devops/).

**Comment by purple-lemon** [comment]
For anyone who want to get rid from this annoying issue, need to disable IPv6:
https://stackoverflow.com/questions/67230241/fatal-unable-to-access-https-dev-azure-com-xxx-openssl-ssl-connect-connec/69712045#69712045
