### ISSUE TITLE
Support `httpcookieFile`

### ISSUE THREAD

**Issue by miya789** [git-ecosystem/git-credential-manager#1160]
### Feature description

Could you please make GCM read cookie files in libcurl format as well as the Git command[^git-cookie]?
When I issue an OAuth2 token by GCM, the communication to the path /oauth/ is not working well because it is not Git that GCM wraps, but GCM that does not support cookies accesses it.
I want to use this because I need to access the Git server behind the Reverse Proxy with Authenticator for a special reason.

I thought about implementing it myself, but Git is calling curl, while GCM is an HTTPClient connection using C#, and it seemed difficult to implement, so I would appreciate it if you could help me.

[^git-cookie]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpcookieFile

**Comment by ldennington** [comment]
Implementing this will require parsing the cookie file format (see [here](https://github.com/curl/curl/blob/master/docs/HTTP-COOKIES.md#cookie-file-format)) and setting the cookies in the `CookieContainer` on the `HttpClient`. We would welcome a contribution from the community though! Hopefully the `help-wanted` label will attract some interest.

**Comment by mjcheetham** [comment]
Closing this issue as the support was added in #1251, and will be available in the next release! :-)
