### ISSUE TITLE
How to install GCM on a remote HPC without root permission

### ISSUE THREAD

**Issue by jajupmochi** [git-ecosystem/git-credential-manager#1183]
### Version

2.0.935

### Operating system

Linux

### OS version or distribution

CentOS 7.9.2009.x86_64

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Everything works out.

### Actual behavior

git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: No credential store has been selected.

**Comment by ldennington** [comment]
Which method are you trying to use to install? The Debian package and installing from source require root permissions, so we'd recommend installing with the [latest tarball](https://github.com/git-ecosystem/git-credential-manager/issues/1139). Let us know if that works.
