### ISSUE TITLE
GCM asks to Sign In to GitHub on macOS after a short while

### ISSUE THREAD

**Issue by iskeld** [git-ecosystem/git-credential-manager#1193]
### Version

2.0.931+f99d745b98

### Operating system

macOS

### OS version or distribution

macOS 13.3 arm64

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Git credential manager should save the credentials and reuse them for a longer time. 

### Actual behavior

Right now, it asks to Sign In again after about 30 minutes.

GCM installed via brew. I tried reinstalling but it didn't help

**Comment by ldennington** [comment]
Can you please provide diagnostic and trace information? You can get trace logs by setting the environment variables GCM_TRACE=1 and GIT_TRACE=1 and re-running your Git command. You can get diagnostic information by running `git-credential-manager diagnose`.

Also is this happening regularly on a 30 minute cadence? When did this behavior start?

**Comment by ccocchiaro** [comment]
I have the same issue.

**Comment by iskeld** [comment]
It seems that it has ceased. Strange, maybe it was something with the github. I'll close the issue for now, if it happens again I'll provide the trace

**Comment by iskeld** [comment]
I'm reopening the issue as it started happening again. Like the last time - it's totally random. Only I think it happens more often. 
I think #1249 is the same issue.

I'm attaching the trace log 
[git.txt](https://github.com/git-ecosystem/git-credential-manager/files/11469458/git.txt)

And gcm diagnose log (only with env variables removed)
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/11469461/gcm-diagnose.log)

**Comment by iskeld** [comment]
Hi @ldennington it started happening again without any obvious reason (I wasn't using github for a while so perhaps that's why it wasn't happening) so I've attached all the necessary data. It also seems that I'm not the only one #1249

**Comment by mjcheetham** [comment]
Are you using Xcode 14.3?

> It seems that it has ceased. Strange, maybe it was something with the github. I'll close the issue for now, if it happens again I'll provide the trace

We've identified an issue with the keychain interaction of GCM when started inside of Xcode 14.3 and are actively investigating. When Xcode 14.3 is open the in background, with the default settings, it periodically runs a `git fetch` (with GCM failing to access the keychain) and this may be the root of the problems you are seeing.

See https://github.com/git-ecosystem/git-credential-manager/issues/1157

**Comment by iskeld** [comment]
@mjcheetham yup, I'm using XCode 14.3. So that might be it. Thanks

**Comment by mjcheetham** [comment]
> yup, I'm using XCode 14.3.

> I'm using Xcode 14.3 as well, and I'm still seeing this.

We've identified an issue with the keychain interaction of GCM when started inside of Xcode 14.3 and are actively investigating.

In the mean time, disabling the 'auto fetch' feature in Xcode will stop these unexpected 'nuking' of the keychain entry, and avoiding using `fetch` or `push` from Xcode.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/5658207/a88501c1-8a15-49dc-9ca6-e35cb26a5292)

**Comment by mjcheetham** [comment]
**Update:**

As mentioned in #1157, we have confirmed that as of Xcode 15 beta 4, the issue has been resolved.

Until Xcode 15 is fully released, you can either continue to disable the auto-fetch functionality in Xcode 14.3, or downgrade to Xcode 14.2.
