### ISSUE TITLE
Constant reprompt for HTTPS authentication credentials via Gittyup after installation of `git-credential-manager`

### ISSUE THREAD

**Issue by rokejulianlockhart** [git-ecosystem/git-credential-manager#1210]
0.	**Version**

	`2.0.935+8b4735fc7b`

0.	**Operating system**

	```pwsh
	$IsLinux
	```

	```log
	True
	```

0.	**OS version or distribution**

	```pwsh
	uname -a
	```

	```log
	Linux RQN6C6 6.2.10-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr  6 10:36:55 UTC 2023 (ba7816e) x86_64 x86_64 x86_64 GNU/Linux
	```

0.	**Git hosting provider(s)**

	GitLab

0.	**Other hosting provider**

	https://gitlab.com/rokejulianlockhart/RTBJK9

0.	**(Azure DevOps only) What format is your remote URL?**

	None

0.	**Can you access the remote repository directly in the browser?**

	Yes, I can access the repository.

0.	**Expected behavior**

	I shouldn't be prompted more than once, surely?

0.	**Actual behavior**

	I'm prompted for every action.

0.	**Logs**

	```pwsh
	WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
	```

	```log
	WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE: The term 'WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE' is not recognized as a name of a cmdlet, function, script file, or executable program.
	Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
	```

**Comment by rokejulianlockhart** [comment]
Uninstalling remediates the problem.

**Comment by Joekie030** [comment]
.?

**Comment by ldennington** [comment]
@rokejulianlockhart - since uninstallation worked can we close this issue? Or is further action needed?

**Comment by rokejulianlockhart** [comment]
@ldennington, of course, more work is needed. How is this project, which purports to be the eventual successor to the current fragmented authentication system, not requiring improvement if the sole fix is to uninstall it…?

**Comment by ldennington** [comment]
Closing stale issue. If this is still a problem, please ensure you have installed the latest version. If the issue persists after that, please open a new issue ensuring you include the logs requested in the issue template.
