### ISSUE TITLE
problem in sending data to central repo (github)

### ISSUE THREAD

**Issue by mohidsaqib** [git-ecosystem/git-credential-manager#1218]
Im using aws linux , i want to send data from my local repo to central repo (github). how can i see my credentials .

**Comment by ldennington** [comment]
Closing this due to lack of information. Please instead fill out [this issue template](https://github.com/git-ecosystem/git-credential-manager/issues/new?assignees=&labels=auth-issue&template=auth-issue.yml) to give maintainers enough information to investigate further.
