### ISSUE TITLE
git-credential-manager doesn't run on MacOS Ventura

### ISSUE THREAD

**Issue by ccope** [git-ecosystem/git-credential-manager#1221]
When I try to run I get the following error message:
```
Failed to resolve full path of the current executable []
```

I think this has something to do with symlink behavior on MacOS, executing the target by hand works (/usr/local/share/gcm-core/git-credential-manager).

Installation method: package from the Github releases page
Mac OS version: 13.3.1 (22E261) (arm64)
git-credential-manager version: 2.0.935

**Comment by ccope** [comment]
Also running the command with sudo works, and the symlink permissions appear to be 750

**Comment by ccope** [comment]
`sudo chmod -h a+rx /usr/local/bin/git-credential-manager` seems to fix the problem

**Comment by mjcheetham** [comment]
How did you install GCM? Did you run the `.pkg` with Installer, extract the tar.gz, or via Homebrew?

**Comment by ccope** [comment]
I used the .pkg installer

**Comment by ccope** [comment]
Ok I think this is actually a brew bug, the same behavior just happened with docker on some of my coworkers machines.
