### ISSUE TITLE
Your browser is not supported or up-to-date when renewing credentials for AzureDevOps

### ISSUE THREAD

**Issue by omri-suissa-clearmash** [git-ecosystem/git-credential-manager#1226]
### Version

Git-2.40.1-64-bit

### Operating system

Windows

### OS version or distribution

Windows 10

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

To be able to authenticate...

### Actual behavior

![image](https://user-images.githubusercontent.com/101049045/234822059-c9b8e674-6be3-41e8-b8aa-c6752e73319f.png)
after entering my credentials. It seems that GCM is using IE instead of Edge to host the Azure AD authentication.

**Comment by Neutrino-Sunset** [comment]
This broken version of the Git Credential Manager appears to be bundled in the current release of Git For Windows.

I've tried versions 2.40.1  2.40.0  2.39.2  and it's failing in the saem way in all of them. So how do we get a version that works?

**Comment by martijn-van-den-bergh** [comment]
I have the same issue, dont understand why this issue is closed without explanation?

**Comment by cookbr** [comment]
@omri-suissa-clearmash Care to elaborate on why you closed this out?

**Comment by omri-suissa-clearmash** [comment]
I found that the issue was related to AzureDevOps login and not to git-credential-manager. MS support solve this issue by resetting some settings in my account (MFA).
It would be nice if git-credential-manager would use a modern browser anyway, but the problem was a wrong configuration of the devops MFA (not sure what exactly, they reset it from their side).

**Comment by zuzhal** [comment]
I have the same issue, @omri-suissa-clearmash. Could you please elaborate on what you reset? Deleted and readded MFA?

**Comment by omri-suissa-clearmash** [comment]
I'm not sure, the MS support did it on their side...

**Comment by Erre35** [comment]
Select Chrome as your default browser, and run:

git config --global credential.msauthFlow system
