### ISSUE TITLE
Announcing GCM's new roadmap!

### ISSUE THREAD

**Issue by Whitecockl** [git-ecosystem/git-credential-manager#1237]
### Discussed in https://github.com/git-ecosystem/git-credential-manager/discussions/1203

<div type='discussions-op-text'>

<sup>Originally posted by **ldennington** April 17, 2023</sup>
Hello GCM community! 👋

We are excited to announce that we’ve begun maintaining a [roadmap](https://github.com/git-ecosystem/git-credential-manager/milestones) of planned GCM features. 💡**Pro tip:** When viewing the roadmap, choose **Furthest due date** from the **Sort** menu in the upper-right corner to view the milestones in ascending order.

We hope this will help bring clarity on the planned efforts of the project and their timelines to you all. There are a few things to note:

1. In an effort to stay aligned with the Git project, we’ve created milestones that coincide with Git’s upcoming releases. Our goal is to consistently publish concrete plans for the next two releases, with a new milestone created each time a release completes.
0. Items that we’re tracking but haven’t yet been assigned to a release will fall into the **Future** milestone.
0. This roadmap is meant to track major projects. While they are not tracked on the roadmap, project maintainers will continue to address/allocate time for bugs and questions as part of their weekly review meetings.

Many thanks to @hickford for recommending this approach!

Questions? Comment below! We’re all ears 👂.</div>

**Comment by ldennington** [comment]
Closing, as there is no actionable information in this issue.

@Whitecockl - if you're new to GitHub and experimenting, please [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) in your account and use that for your personal learning.
