### ISSUE TITLE
What happened to the login screen? All text is gone ... (Linux)

### ISSUE THREAD

**Issue by eduarddejong** [git-ecosystem/git-credential-manager#1256]
See the screenshot.

Note that the buttons still work. It's just that I have hardly any idea what I am clicking.

This is on Linux, using the Xfce desktop.

![afbeelding](https://github.com/git-ecosystem/git-credential-manager/assets/86660027/41ebf892-7535-48cb-b977-fbe061be392b)

**Comment by ldennington** [comment]
Can you try running the following and see if it renders aftwerward?

`sudo apt-get install ttf-mscorefonts-installer`

**Comment by eduarddejong** [comment]
Sorry, I haven't paid attention to this issue anymore.

I tested it now. However I am on Arch Linux so apt-get is not working in my case, but I installed the corresponding Microsoft proprietary fonts from AUR and indeed it works!
Apparently I didn't have these yet.

However, I would not expect from such a general Github authentication tool to require proprietary fonts.
Would be great to at least have a fall back to open source fonts if possible.

**Comment by ldennington** [comment]
This is something we can investigate with Avalonia (as to why the default fluent theme doesn't have an appropriate fallback font).

**Comment by mjcheetham** [comment]
[The .NET runtime isn't officially supported on Arch Linux](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux), so I don't imagine that the Avalonia UI project would definitely support Arch. Knowing that the default Arch install is super-minimal it's not surprising that Avalonia is expecting some common fonts to be there.

As a rule of thumb, GCM only really supports the same distros that .NET itself does, so we're probably not going to be able to do much here. I'm glad that the workaround of installing the Microsoft fonts (or the open-source Google ones!) worked.
