### ISSUE TITLE
GCM does not support CBL-Mariner OS

### ISSUE THREAD

**Issue by lanrobin** [git-ecosystem/git-credential-manager#1257]
### Feature description

![image](https://github.com/git-ecosystem/git-credential-manager/assets/1825760/e88be1c6-3c7a-49dd-ace3-0047f297c84c)

It doesn't support Mariner OS
ERROR: Unsupported Linux distribution: mariner

**Comment by ldennington** [comment]
Because it is build on .NET, GCM purposefully only supports the same Linux distributions that .NET [officially supports](https://learn.microsoft.com/en-us/dotnet/core/install/linux#packages). I'd recommend using an authentication alternative (like SSH) for your Mariner OS distribution.

**Comment by amireshaghian** [comment]
@lanrobin

**Comment by lanrobin** [comment]
Thanks, we can easy make it by adding a support distro:

![image](https://github.com/git-ecosystem/git-credential-manager/assets/1825760/a3eeac55-2f3b-48c2-885b-d514f0ee59db)
