### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by tuanggo** [git-ecosystem/git-credential-manager#1272]
ok

_Originally posted by @tuanggo in https://github.com/git-ecosystem/git-credential-manager/issues/1238#issuecomment-1560246961_

**Comment by ldennington** [comment]
Closing, as there is no actionable information in this issue.

@tuanggo - if you are just learning GitHub, please feel free to [fork this repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and continue experimenting there.
