### ISSUE TITLE
Support Azure managed identity authentication with AzureDevOps repos

### ISSUE THREAD

**Issue by elbardel** [git-ecosystem/git-credential-manager#1313]
### Feature description

AzureDevOps released in public preview a feature to enable [authentication with Azure Active Directory service principals & managed identities](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops) and they are encouraging people to use for automation instead of PATs.

It would be useful to have support for managed identities authentication in git-credential-manager, in the same way it already supports AAD authentication with users.
The managed identity client id could be provided in the configuration.

This would greatly simplify setting up a repo for automation, and everything would seemlessly after setting up the git-credential-manager configuration.

**Comment by mjcheetham** [comment]
We've now merged in support for both Managed Identity and Service Principal-based authentication with Azure DevOps. At the moment we project it to make it in the GCM 2.4.0 release in the November-timeframe.
