### ISSUE TITLE
Generic OAuth: Git only sends credentials on third request 

### ISSUE THREAD

**Issue by lgf10** [git-ecosystem/git-credential-manager#1341]
### Version

2.2.1

### Operating system

Windows

### OS version or distribution

Windows 10

### Git hosting provider(s)

Other - please describe below

### Other hosting provider

Generic OAuth (self-hosted Keycloak)

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

When running commands like "git pull" in a repository which is configured to use a [generic OAuth provider](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/generic-oauth.md):

➡️ Git sends the **first** request with `Authorization: Basic` containing the username and the access token as the password
✔️ The server validates the token and sends the expected Git response

### Actual behavior

➡️ Git sends the first request **without** the Authorization header
❌ The server responds with 401 and `WWW-Authenticate: Basic`
➡️ Git sends the seconds request with `Authorization: Basic` containing the username and an **empty password**
❌ The server responds with 401 and `WWW-Authenticate: Basic`
➡️ Git sends the third request with `Authorization: Basic` containing the username and the access token as the password
✔️ The server validates the token and sends the expected Git response

This needlessly increases the roundtrip time.
Note that the server-side authentication is a custom implementation, I would be happy to make changes if necessary. But this seems more of a client-side issue to me.

**Comment by ldennington** [comment]
The behavior you are describing is unexpected. What _should_ happen is Git should make the first request without the header (Git doesn't know if this is a public or private repo, so always makes this first unauthenticated request). After receiving the first 401, it should consult a credential helper (GCM), at which point we will perform authentication and return a token to Git.

The second request you are describing is the one that seems strange. Can you reproduce this with the following environment variables set so we can look at what Git and GCM are doing?

```
set GIT_TRACE=C:\Users\USERNAME\git.log
set GCM_TRACE=C:\Users\USERNAME\git.log
set GIT_TRACE_CURL=C:\Users\USERNAME\git.log
```

Please review the output log and remove any sensitive information before attaching. Git/GCM try to avoid logging passwords and other secrets, but it is always worth an extra check.

**Comment by lgf10** [comment]
Thank you for taking a look at this 😄 I have uploaded a log file created with GIT_TRACE_REDACT=0 to show Authorization headers. Private information has been manually redacted.

[First request](https://gist.github.com/lgf10/8e0d83e1e71d4c4502315ee93480716f#file-log-txt-L67) - Authorization header is missing
[Second request](https://gist.github.com/lgf10/8e0d83e1e71d4c4502315ee93480716f#file-log-txt-L135) - Authorization header with blank password
[Third request](https://gist.github.com/lgf10/8e0d83e1e71d4c4502315ee93480716f#file-log-txt-L185) - Authorization header with token

Are there options (e.g. in .gitconfig) to always send the token in the first request? We always require authorization and would like to avoid the delay of the additional requests (0.42 seconds in my example, possibly larger for people with higher latency).

**Comment by lgf10** [comment]
I forgot `GCM_TRACE` in the first log, so here's another one:
[First request](https://gist.github.com/lgf10/40e85117cb214e47f5a80b9977913ae6#file-log2-txt-L70)
[Second request](https://gist.github.com/lgf10/40e85117cb214e47f5a80b9977913ae6#file-log2-txt-L138)
[Third request](https://gist.github.com/lgf10/40e85117cb214e47f5a80b9977913ae6#file-log2-txt-L211)

**Comment by ldennington** [comment]
@lgf10 - thanks for sharing! We think it might be the case that you have another credential helper configured or there's an extra header configuration set and Git is picking it up. Can you please share output from the following command so we can investigate further?

`git config --list --show-origin`

**Comment by ldennington** [comment]
We took another look at the logs/config and determined that GCM is only consulted after the second request is made. The third request succeeds with GCM's input. The unexpected second request is outside the scope of GCM and appears to be something strange happening within Git. Please file a [bug report](https://github.com/git-for-windows/git/issues/new/choose) with the Git for Windows project.
