### ISSUE TITLE
Auth prompts on every git command

### ISSUE THREAD

**Issue by varshini-elayappen** [git-ecosystem/git-credential-manager#1342]
### Version

GCM version - 2.0.785+6074e4e3d3

### Operating system

Windows

### OS version or distribution

Windows 10

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Recently there have been some issues related to excessive auth prompts on every git command. Even the `git status` is resulting in auth prompts in some cases. There are multiple folks in Office org in Microsoft seeing this issue. Is this a known issue?

### Actual behavior

Repeated authentication prompts with every git command

**Comment by mjcheetham** [comment]
Closing. We investigated this offline with the user and found out that the issue lies with the server returning unexpected 401s.
