### ISSUE TITLE
GCM-Linux Kerberos integration

### ISSUE THREAD

**Issue by SanSanch5** [git-ecosystem/git-credential-manager#1353]
### Version

2.2.2

### Operating system

Linux

### OS version or distribution

Ubuntu 20.04

### Git hosting provider(s)

Azure DevOps Server (TFS/on-prem)

### (Azure DevOps only) What format is your remote URL?

https://dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Credential manager passes current AD user name and its authentication info from kerberos ticket to TFS Git

I joined my machine to local AD realm and able to use credentials with local network shares and other resources but not with Git.
I'd expect credential.credentialStore = kerberos option but couldn't find one. I saw authority = kerberos, but it didn't work and also marked `deprecated`.
So it would be nice to have integration of GCM with Active Directory via kerberos on Linux.

Any plans of doing it?

If it's already supported please tell me I can attach some logs (but all of those tell than the requested resource forbit anonymous access).

N.B. I also have googled this issue a lot and gave up eventually (configured gpg/pass).

### Actual behavior

Credential manager doesn't pass current AD user name and its authentication info from kerberos ticket to TFS Git

**Comment by SanSanch5** [comment]
I also found this issue https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/607
But it's been 5 years and now we use another brand new GCM... :)

**Comment by ldennington** [comment]
GCM doesn't actually perform any Kerberos or NTLM authentication. We instead rely on Git's use of `libcurl` to perform SPNEGO (kerberos/Windows/NTLM authentication). Support for SPNEGO requires that the Git you are using be built with a `libcurl` version that has also been built with such support. Git for Windows has this built-in, but I am not sure of your particular version of Git - this is distro-dependent.

https://curl.se/libcurl/c/CURLOPT_HTTPAUTH.html#CURLAUTHNEGOTIATE
>You need to build libcurl with a suitable GSS-API library or SSPI on Windows for this to work.

We don't currently have any plans to bring native SPNEGO auth to GCM itself.
