### ISSUE TITLE
“Once it's installed and configured,”

### ISSUE THREAD

**Issue by daveyostcom** [git-ecosystem/git-credential-manager#1357]
### Feature description

The ReadMe should say want it means to be configured.  Apparently something has to happen in `~/.gitconfig`, but what exactly?  The installer on macOS also hints but does not explain; instead it delegates to the ReadMe.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/8748/249f5df9-7d95-4ad1-9f67-6f5192e421b6)

**Comment by daveyostcom** [comment]
The [Install instructions](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md) also don’t illuminate re `.gitconfig`.

**Comment by ldennington** [comment]
By `configure`, we mean setting the `credential.helper` config to the GCM exe as well as `credential.useHttpPath` to `true` for dev.azure.com remotes. We would welcome an update to the `README` and/or help documentation for the `configure` command clarifying this.

**Comment by daveyostcom** [comment]
I can’t offer a fix because what you say is not concrete enough for me to understand and I’m on macOS.  This is why I posted this issue.  Thanks.

**Comment by mjcheetham** [comment]
Hello @daveyostcom,

We've updated the FAQs to include information about what the `configure` and `unconfigure` commands do, and link to the FAQs from the macOS installer pages.
