### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by ALJHONQ** [git-ecosystem/git-credential-manager#1360]
### Version

Beta

### Operating system

Windows

### OS version or distribution

Android version

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Authentication git complete 

### Actual behavior

UI freeze 

### Logs

Git credentials manager diagnose

**Comment by mjcheetham** [comment]
This issue does not contain any actionable information or details as to the issue.

> **OS version or distribution**
> Android version

There is no Android version of GCM. This ticket appears to have been opened in error - closing.
