### ISSUE TITLE
Cannot init submodules from WSL2 terminal

### ISSUE THREAD

**Issue by frsrgrrw** [git-ecosystem/git-credential-manager#1367]
### Version

2.2.2

### Operating system

Windows

### OS version or distribution

Windows 11 Pro

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I am trying to clone a private repo that I own (Foo.git) from GitHub that has a submodule, also private (Bar.git), I am trying to init with the submodule. I expect both repos to be populated with contents. 

Cloning both individually works without error.  e.g.

```
git clone git@github.com:frsrgrrw/Foo.git

git clone git@github.com:frsrgrrw/Bar.git
```

My gcm is setup in Windows (with the config in WSL pointing to the Windows gcm executable) and I am running, in the WSL terminal, the following command:
```
git clone --recurse-submodules git@github.com:frsrgrrw/Foo.git
```

### Actual behavior

I get the error: 

```
Cloning into '/home/user/Foo/Bar'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:frsrgrrw/Bar.git' into submodule path '/home/user/Foo/Bar' failed
Failed to clone 'Bar'. Retry scheduled
Cloning into '/home/user/Foo/Bar'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:frsrgrrw/Bar.git' into submodule path '/home/user/Foo/Bars' failed
Failed to clone 'Bar' a second time, aborting
```

**Comment by mjcheetham** [comment]
Hello @frsrgrrw,

This looks like you are cloning a repository via SSH, not HTTPS. GCM only applies to HTTPS remotes, not SSH.

> git@github.com: Permission denied (publickey).

The error here looks like something to do with permissions around your SSH keys.
