### ISSUE TITLE
credentials 

### ISSUE THREAD

**Issue by github-chief-commander** [git-ecosystem/git-credential-manager#1390]
### Version

18

### Operating system

macOS

### OS version or distribution

Developer version

### Git hosting provider(s)

Azure DevOps, Azure DevOps Server (TFS/on-prem), Bitbucket Cloud, Bitbucket Server/DC, GitHub, GitHub Enterprise Server, GitLab, Other - please describe below

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Financial 

### Actual behavior

Financial 

### Logs

Financial

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.
