### ISSUE TITLE
Multiple login windows

### ISSUE THREAD

**Issue by kefahB** [git-ecosystem/git-credential-manager#1405]
### Version

2.0.785+6074e4e3d3

### Operating system

macOS

### OS version or distribution

Ventura 13.5

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

One login window open

### Actual behavior

multiple login windows, see below

<img width="1728" alt="Capture d’écran 2023-09-08 à 23 47 45" src="https://github.com/git-ecosystem/git-credential-manager/assets/18148534/2b3602bd-3f20-43e9-8c38-f1311e3def37">

**Comment by mjcheetham** [comment]
Hello!

> **Version**
> 2.0.785+6074e4e3d3

Before we continue investigating the issue, please can you try updating the version of GCM you have installed? There have been many bug fixes and changes since 2.0.785 (July 2022).

**Comment by ldennington** [comment]
Closing with assumption upgrade fixed. If you continue to see the problem, please open a new issue.
