### ISSUE TITLE
Azure DevOps auth dialog missing

### ISSUE THREAD

**Issue by jochenhz** [git-ecosystem/git-credential-manager#1410]
### Version

2.3.2

### Operating system

macOS

### OS version or distribution

Ventura 13.4 (22F66)

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I have upgrade from 2.0 to the latest version of GCM

running `git clone https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production 
` should open the Azure DevOps / Microsoft auth dialog 

![64f9b52347c2731b07e65511_120](https://github.com/git-ecosystem/git-credential-manager/assets/59531156/75b487cc-5e81-4504-a265-4b64c22f42cb)

### Actual behavior

With 2.3.2 the fallback dialog opens instead

![image](https://github.com/git-ecosystem/git-credential-manager/assets/59531156/4e6597ea-3b36-409d-8abb-f4b5aa964e28)

### Logs

jochenhunz@Jochens-MacBook-Pro new GCM % GIT_TRACE=1 git clone https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production 
15:05:39.231361 git.c:439               trace: built-in: git clone 'https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production'
Cloning into 'Virtual%20Production'...
15:05:39.242676 run-command.c:655       trace: run_command: git remote-https origin 'https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production'
15:05:39.250821 git.c:725               trace: exec: git-remote-https origin 'https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production'
15:05:39.251165 run-command.c:655       trace: run_command: git-remote-https origin 'https://jhunz@dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production'
15:05:39.821189 run-command.c:655       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager get'
15:05:40.064441 git.c:439               trace: built-in: git config --null --list
15:05:40.302481 git.c:439               trace: built-in: git version
15:05:40.331766 git.c:439               trace: built-in: git config --null --type=path 'credential.https://dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production.uiHelper'
15:05:40.345691 git.c:439               trace: built-in: git config --null --type=path 'credential.dev.azure.com/jhunz/Virtual%20Production/_git/Virtual%20Production.uiHelper'
15:05:40.366443 git.c:439               trace: built-in: git config --null --type=path 'credential.https://dev.azure.com/jhunz/Virtual%20Production/_git.uiHelper'
15:05:40.387378 git.c:439               trace: built-in: git config --null --type=path 'credential.dev.azure.com/jhunz/Virtual%20Production/_git.uiHelper'
15:05:40.400204 git.c:439               trace: built-in: git config --null --type=path 'credential.https://dev.azure.com/jhunz/Virtual%20Production.uiHelper'
15:05:40.412024 git.c:439               trace: built-in: git config --null --type=path 'credential.dev.azure.com/jhunz/Virtual%20Production.uiHelper'
15:05:40.423513 git.c:439               trace: built-in: git config --null --type=path credential.https://dev.azure.com/jhunz.uiHelper
15:05:40.435036 git.c:439               trace: built-in: git config --null --type=path credential.dev.azure.com/jhunz.uiHelper
15:05:40.445862 git.c:439               trace: built-in: git config --null --type=path credential.https://dev.azure.com.uiHelper
15:05:40.456436 git.c:439               trace: built-in: git config --null --type=path credential.dev.azure.com.uiHelper
15:05:40.468298 git.c:439               trace: built-in: git config --null --type=path credential.https://azure.com.uiHelper
15:05:40.480112 git.c:439               trace: built-in: git config --null --type=path credential.azure.com.uiHelper
15:05:40.495232 git.c:439               trace: built-in: git config --null --type=path credential.uiHelper

**Comment by ldennington** [comment]
@jochenhz can you run the following and attach the results?

`git-credential-manager diagnose`
`git config --list --show-origin`

Also, just as a heads up, you will not see a dialog on macOS for Azure Repos. However, you should see a browser tab prompting you to log in with your Microsoft credentials.

**Comment by jochenhz** [comment]
Hey @ldennington 

please find the files attached. Thanks :)

[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/12653702/gcm-diagnose.log)
[config.log](https://github.com/git-ecosystem/git-credential-manager/files/12653706/config.log)

**Comment by mjcheetham** [comment]
Hello @jochenhz!

Thanks for those logs. Looking at your config I see this line:

```text
file:/Users/jochenhunz/.gitconfig	credential.https://dev.azure.com/jhunz.provider=generic
```

This setting explains why you are seeing the fallback/generic credential UI.

Not entirely sure how this was set, but if you unset this config option then you should see the correct login UI again!

```shell
git config --global --unset credential.https://dev.azure.com/jhunz.provider
```

**Comment by jochenhz** [comment]
Ah, thank you so much! That does the trick.
It seems that the setting is set by the GCM. One of our scripts calls `git-credential-manager set` and does not set `path=jhunz/Virtual%20Production/_git/Virtual%20Production` as it is not documented on the [git documentation](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage)

Do I understand it correctly that setting the `path` is only required / possible because of `credential.https://dev.azure.com.usehttppath=true`

Thanks!
