### ISSUE TITLE
Multiple prompts for permissions to use current account

### ISSUE THREAD

**Issue by smaillet-ms** [git-ecosystem/git-credential-manager#1411]
### Version

2.3.2

### Operating system

Windows

### OS version or distribution

Windows 11 22H2

### Git hosting provider(s)

Azure DevOps

### Other hosting provider

None yet (Part of the problem)

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I expect to be able to logon and use my computer uninterrupted. Even when not using any git functionality.

### Actual behavior

When I logon to my computer I'm greeted by numerous Git credential manager pop-ups (3 in less than 2 minutes today). Worse they come along at completely random points in time when I'm not doing anything related to GIT or development. This is a HUGE security risk as I have no clue what is prompting me for permissions. I already gave git credentials permissions. When I click on the link for more details on OS accounts - I get a lot of techno babble - but no real help. I've set the system wide env var `GCM_MSAUTH_USEDEFAULTACCOUNT=true` in git config I have `credential.msauthUseDefaultAccount=true` AND `credential.modalprompt=false` but I still get these VERY annoying prompts all day long at random times. How is anyone supposed to get work done with these constant annoying interruptions - how do I make these stop!

### Logs

No logs (Too much work to redact proprietary info - and it isn't clear what's a risk - so I'm including nothing to be safe)
![Untitled](https://github.com/git-ecosystem/git-credential-manager/assets/8934567/b81d78c7-bddb-456c-9743-c595e86369e0)

**Comment by ldennington** [comment]
Duplicate of https://github.com/git-ecosystem/git-credential-manager/issues/1415
