### ISSUE TITLE
Git Credential Manager keeps popping up

### ISSUE THREAD

**Issue by AlbertGuan9527** [git-ecosystem/git-credential-manager#1415]
### Version

2.3.2

### Operating system

Windows

### OS version or distribution

x64, OS build 23550.1000

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

The git credential manager won't pop up.

### Actual behavior

 The Git Credential Manager keeps popping our every couple of minutes, Click at the "Continue" or the "X" seems have no difference to my normal development work.

### Logs

[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/12651312/gcm-diagnose.log)

**Comment by AlbertGuan9527** [comment]
Hi Lessley,

Yes, it solves the problem, sorry about the delay.

Regards,
Albert

**Comment by ldennington** [comment]
No problem, thanks for your response!
