### ISSUE TITLE
Host provider auto-detection regarding GitLab

### ISSUE THREAD

**Issue by HarryHartmann** [git-ecosystem/git-credential-manager#1434]
### Discussed in https://github.com/git-ecosystem/git-credential-manager/discussions/1433

<div type='discussions-op-text'>

<sup>Originally posted by **HarryHartmann** October  9, 2023</sup>
In my eco-environment I am trying to apply standard git command to add a submodule:

`git submodule add <url_to_git_repo> <local_dir_path>`

The repo _url_to_git_repo_ is a GitLab hosted repository. The "git submodule add" command execution responds with error message: 

warning: failed to probe 'URL2REPO' to detect provider
warning: The ServicePointManager does not support proxies with the URL2REPO scheme.
warning: see https://aka.ms/gcm/autodetect for more information.
fatal: The ServicePointManager does not support proxies with the URL2REPO scheme.

"Git Credential Manager (GCM) supports authentication with multiple different Git host providers including: GitHub, Bitbucket, and Azure Repos." I don't see GitLab listed as supported Git host.

What do I miss to get it working? Any hint helps, thnx, Harry.
</div>

**Comment by rimrul** [comment]
> warning: see https://aka.ms/gcm/autodetect for more information.

That's the big hint right there. That link leads to https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/autodetect.md

That document has a "Manual Configuration" section

https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/autodetect.md#manual-configuration.

That section details how to manually configure the `gitlab` provider.

**Comment by ldennington** [comment]
@HarryHartmann - can you confirm that manual configuration resolved your issue?

**Comment by ldennington** [comment]
Closing due to lack of response.
