### ISSUE TITLE
Ripple shares have been restocked on Lingto : Ripple

### ISSUE THREAD

**Issue by bidex32** [git-ecosystem/git-credential-manager#1454]
Lingto
Linqto, a platform that sells shares of private companies, has announced that Ripple shares have been restocked and are now available for purchase on its platform.

This marks the second time this month that the shares of the blockchain-based payment network, Ripple, have been made available on Linqto.

You probably noticed that there has been rising speculation regarding Ripple's plans for an initial public offering (IPO). These discussions are not new and can be traced back to 2018.

Tbh, I never bought any shares, but this might be something that I will be willing to try. I'm more into using blockchain and crypto for actual stuff, like CertiK or Neurochain. If you're new to crypto and want a simple way to invest, crypto shares on reputable exchanges are a solid choice. They provide a convenient onramp into the market. However, if you're more experienced, value privacy and control, or believe in the principles of decentralization, using blockchain directly might be your preferred route.

In many cases, a combination of both approaches can offer the best of both worlds. Diversify your investments with crypto shares, and then explore the blockchain directly to experience the true power and potential of cryptocurrencies.

Now that Ripple has gained clarity regarding their standing with the SEC, it remains to be seen whether or not they will proceed with an IPO.

What do you think?

**Comment by bidex32** [comment]
Wow

**Comment by ldennington** [comment]
Closing - content is irrelevant to GCM.
