### ISSUE TITLE
gh auth login seems to depend on gcm, does it?

### ISSUE THREAD

**Issue by kaddkaka** [git-ecosystem/git-credential-manager#1462]
### Version

-

### Operating system

Linux

### OS version or distribution

Ubuntu 22.04

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Access to `git fetch` and `git push` in my terminal. But after `gh auth login` I'm still not able to do `git fetch`.

```
> gh auth login
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? Yes
? What is your preferred protocol for Git operations? HTTPS
? Authenticate Git with your GitHub credentials? Yes
? How would you like to authenticate GitHub CLI? Paste an authentication token
Tip: you can generate a Personal Access Token here https://github.com/settings/tokens
The minimum required scopes are 'repo', 'read:org', 'workflow'.
? Paste your authentication token: ***********************************- gh config set -h github.com git_protocol https
✓ Configured git protocol
✓ Logged in as kaddkaka
> git push
/usr/local/share/gcm-core/git-credential-manager-core get: 1: /usr/local/share/gcm-core/git-credential-manager-core: not found
Username for 'https://github.com':
Password for 'https://github.com':
/usr/local/share/gcm-core/git-credential-manager-core erase: 1: /usr/local/share/gcm-core/git-credential-manager-core: not found
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/kaddkaka/dotfiles.git/'
```

### Actual behavior

git starts asking for username and password and then gives error related to `git-credential-manager-core`

**Comment by mjcheetham** [comment]
Hello! A few questions to help diagnose the issue here..

- Have you installed GCM at any point in the past or present? If so, how did you install?
   - Can check in `/usr/local/share/gcm-core/` for the `git-credential-manager` executable?

- Can you please run the following command and share your Git config? It's possible that `gh` CLI and GCM's setup of Git's credential helper is not correct.

```shell
git config --get-all --show-scope credential.helper
```

**Comment by kaddkaka** [comment]
I see, I have this:
```console
$ ls /usr/local/share/gcm-core/
ls: cannot access '/usr/local/share/gcm-core/': No such file or directory
$ git config --get-all --show-scope credential.helper
global  /usr/local/share/gcm-core/git-credential-manager-core
```
so I guess my gcm installation is missing, but my gitconfig says to use gcm.

**Comment by kaddkaka** [comment]
I removed the credential helper config, now it works. Thanks! :)
