### ISSUE TITLE
Clarify which account the prompt is for

### ISSUE THREAD

**Issue by carlocardella** [git-ecosystem/git-credential-manager#1472]
### Feature description

Certain tools allow to open multiple repositiries, even from different Git sources (GitHub, GitHub enterprise, Azure DevOps etc.): Credential Manager shold specify which account needs authentication, all I get is this and it is always a pain to find the account I need to login to:

![image](https://github.com/git-ecosystem/git-credential-manager/assets/5784415/0e229fba-7d83-4d19-afdc-736db654b4b4)

This prompt is actually from my GitHub Enterprise account, but the dialog window just says GitHub

**Comment by mjcheetham** [comment]
Sadly we're unlikely to be able to fix this 'context' problem as Git itself only gives GCM a small amount of information on the request that needs authenticating.

Git will only provide the protocol and hostname of the remote URL (i.e, `"https://github.com"`) by default.

If you set the `credential.useHttpPath` setting to `true` then Git will also provide credential helpers the full path (i.e, `"https://github.com/owner/repo"`) but this has a change in behaviour - GCM will start storing credentials _specifically for that full repository URL_.. so you'll have separate credentials (and sign-ins) for each repo.

---

> This prompt is actually from my GitHub Enterprise account, but the dialog window just says GitHub

If you are using a GitHub Enterprise Server instance we should display the server hostname, for example:

<img width="488" alt="image" src="https://github.com/git-ecosystem/git-credential-manager/assets/5658207/06049069-3494-41d4-8406-3dc9467e3add">

We cannot differentiate between the different GitHub SKUs that are hosted under https://github.com.

**Comment by mbailey** [comment]
The tool should accommodate users with more than one account on a github.

For enhanced security and clarity, it's good practice to use different GitHub accounts for projects across separate security boundaries, such as work-related and personal endeavors.  Even github.com itself (and the mobile apps) allow you to login to multiple accounts and switch between them. It also appears having a redundant github account might also be a good idea given they may be [randomly suspended](https://twitter.com/defunkt/status/1754610843361362360). 

A user with multiple accounts on github who:

- sets the credential.useHttpPath setting to true
- wants GCM to store credentials specifically for that full repository URL

would benefit from knowing which remote they are being prompted for so they can login with the correct account.
