### ISSUE TITLE
Error when TLS 1.3 enabled in Cloudflare

### ISSUE THREAD

**Issue by JVimes** [git-ecosystem/git-credential-manager#1491]
### Version

2.4.1.0

### Operating system

Windows

### OS version or distribution

Version 22H2 (OS Build 19045.3803)

### Git hosting provider(s)

Other - please describe below

### Other hosting provider

Gitea (self hosted)

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

No error and browser auth works with TLS 1.3 enabled in Cloudflare

### Actual behavior

With TLS 1.3 enabled in Cloudflare:
- Browser reports success but error in console and legacy prompt.

```pwsh
PS> git clone https://gitea.mydomain.com/MyUsername/TestRepo.git
Cloning into 'TestRepo'...
warning: failed to probe 'https://gitea.mydomain.com/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
# >>> Chrome page opens: "Authentication successful You can now close this page."
fatal: An error occurred while sending the request.
fatal: The request was aborted: Could not create SSL/TLS secure channel.
Username for 'https://gitea.mydomain.com':
```

It works with TLS 1.3 _disabled_ in Cloudflare:

```pwsh
PS> git clone https://gitea.mydomain.com/MyUsername/TestRepo.git
Cloning into 'TestRepo'...
# >>> Chrome page opens: "Authentication successful You can now close this page."
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
PS>
```

### Logs

- [tls13-disabled.txt](https://github.com/git-ecosystem/git-credential-manager/files/13698114/tls13-disabled.txt)
- [gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/13698112/gcm-diagnose.log)

**Comment by mjcheetham** [comment]
Just to confirm that you are able to use TLS 1.3 in other application on your computer? And that you are using Windows 11 or later?

GCM on Windows still targets .NET Framework, specifically .NET Framework 4.7.2, which should support the TLS versions of the underlying Windows OS. It should also default to the most secure/newest, as GCM does _not_ specify a specific TLS version, per the [recommendations](https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-net-framework-47-or-later-versions).

**Comment by JVimes** [comment]
Thank you. I'm on Windows 10. I enabled the experimental TLS 1.3 [support](https://community.fortinet.com/t5/FortiGate/Troubleshooting-Tip-how-to-enable-TLS-1-3-in-Windows-10/ta-p/276680) and it seems to work today.
