### ISSUE TITLE
Support SAML authentication on Bitbucket Server (DataCenter)

### ISSUE THREAD

**Issue by agusmba** [git-ecosystem/git-credential-manager#151]
**Feature description**

Bitbucket Server Datacenter supports SAML authentication against an external IDP.

This functionality can also be provided to regular Bitbucket Server by several marketplace plugins.

It would be great if GCMC could include support for this, in order to avoid the need to manually create user tokens for git client authentication.

Thank you!

**Comment by vtbassmatt** [comment]
@agusmba I just created the `help-wanted` label and applied it here. This isn't something we'll build on the core team side, but we would absolutely welcome community contributions.

**Comment by ldennington** [comment]
I believe this was fixed with #607. @mminns, are you able to confirm?
