### ISSUE TITLE
We couldn't send a notification to your phone at this time. Please try again.

### ISSUE THREAD

**Issue by veertien** [git-ecosystem/git-credential-manager#1540]
### Version

2.4.1

### Operating system

Windows

### OS version or distribution

Windows 11

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}@dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

When I fetch the git credential manager pops up.

I go through a flow where I sign in using my device

### Actual behavior

When I fetch the git credential manager pops up.
1. I type in the email of the account I want to use
2. I get a choice for "Work or school account" or "Personal account"
3. I choose my personal (Microsoft) acocunt which is for sure the one that I need
4. I get a screen "Sign in" with a button "Send notification"
5. I click the button
6. I get "Request wasn't sent" We couldn't send a request to your mobile device at this time. Try again to send another request.

**Comment by cgallred** [comment]
I am also experiencing this issue. My URL is of the form `https://{org}.visualstudio.com`. I get the same error as veertien described when using my personal MSA.

**Comment by mjcheetham** [comment]
> We couldn't send a request to your mobile device at this time. Try again to send another request.

Unfortunately this is an error from Microsoft and their auth server, which GCM has no insight or control over.
