### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by kingabnt** [git-ecosystem/git-credential-manager#1550]
https://github.com/kingabnt/release/commit/ec79c26f6942c5d21aae803b1882721db46e7c99

**Comment by kingabnt** [comment]
> https://github.com/kingabnt/release/commit/ec79c26f6942c5d21aae803b1882721db46e7c99

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.

**Comment by kingabnt** [comment]
Duplicate of #1500
