### ISSUE TITLE
Please add support for [includeif "hasconfig:remote.*.url:..."]

### ISSUE THREAD

**Issue by ktetzlaff** [git-ecosystem/git-credential-manager#1581]
I have moved site specific credential options like
``` ini
[credential "https://git.example.com"]
        username = ...
	provider = generic
```
to a separate file which is included in my global git config via `[includeif "hasconfig:remote.*.url:https://git.example.com/**"]`. Unfortunately, GCM doesn't (seem to) properly handle the `hasconfig:remote.*.url:` includeif variant and thus doesn't find my credential config. It then decides to add its own:
``` ini
[credential "https://git.example.com"]
	provider = generic
```
section to the global git config.

If supporting the `includeif` mechanism is not possible, please provide an option to stop GCM from automatically updating git config files (I manage my config via [chezmoi](https://www.chezmoi.io/) which detects and complains about the local change made by GCM each time I update my dotfiles).

**Comment by dscho** [comment]
> Unfortunately, GCM doesn't (seem to) properly handle the `hasconfig:remote.*.url:` includeif variant

Git Credential Manager [asks `git config` to do the honors](https://github.com/git-ecosystem/git-credential-manager/blob/85dab25e2a2dd10defc15e8679dd58982c532f2b/src/shared/Core/GitConfiguration.cs#L130), so if your `git` executable cannot handle that `includeif` construct, that would explain things. Otherwise, please feel free to generate and analyze a trace by using `GCM_TRACE=1`.

**Comment by ktetzlaff** [comment]
Thanks for checking!

I just retested this with GCM 2.5.0 and git 2.43.0 and could not reproduce the problem. Unfortunately, I did not report the versions I used when opening the issue. Based on the date, it should have been GCM 2.4.1. But even with that version, GCM works as expected.

So I'm closing the issue. Sorry for the noise...

**Comment by fernandoweberxf** [comment]
Otimo emulador ps3

**Comment by beingme8583-netizen** [comment]
> credential \"https://git.example.com\"]\n        username = ...\n\tprovider = generic
