### ISSUE TITLE
Github author identity in commits

### ISSUE THREAD

**Issue by TeamBattino** [git-ecosystem/git-credential-manager#1589]
### Feature description

Add a way to use the currently active GitHub account on the repository for the author Identity when trying to commit.

Would stop this from happening without setting the user and email globally. 
![image](https://github.com/git-ecosystem/git-credential-manager/assets/142780545/c8ae15f4-8529-4ea5-9ce6-5c2681b3347f)

**Comment by mjcheetham** [comment]
This error and requirement to set an author is inside of core Git itself, and has nothing to do with GCM. GCM is not involved in any of the local commands such as `commit`.
