### ISSUE TITLE
Allow adding extra scopes to gitlab oauth tokens?

### ISSUE THREAD

**Issue by maxhaton** [git-ecosystem/git-credential-manager#1616]
### Feature description

Currently the authentication with gitlab is done such that the final token only has scopes that let it read and write repositories, it would be useful if one could optionally add to this e.g. read_api and so on, e.g. so other tools authenticating with the same gitlab instance can avoid implementing their own oauth flow.

The change to do so would presumably be trivial, is there a security reason not to?

**Comment by mjcheetham** [comment]
> The change to do so would presumably be trivial, is there a security reason not to?

Tokens managed by GCM should only be used for Git operations.

**Comment by maxhaton** [comment]
> > The change to do so would presumably be trivial, is there a security reason not to?
> 
> Tokens managed by GCM should only be used for Git operations.

And if that operation is a custom git subcommand? Where's the boundary? It would still only be going via the git credential api
