### ISSUE TITLE
git push origin HEAD hangs without any error starting June 5

### ISSUE THREAD

**Issue by gjswalling** [git-ecosystem/git-credential-manager#1632]
### Version

2.5.0+d34930736e131ad80e5690e5634ced1808aff3e2

### Operating system

Linux

### OS version or distribution

Ubuntu 22.04

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}@dev.azure.com/{org}

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I should see my latest commit show up in my branch/PR in ADO after running "git push origin HEAD".
I was able to push changes to my branch yesterday but not today.  

### Actual behavior

Starting today "git push origin HEAD" just hangs - no prompt for login.
I tried git-credential-manager unconfigure and configure but no effect.  
I tried rebooting Ubuntu and verified InTune still connects (compliant).

### Logs
$ git push origin HEAD -v
Pushing to https://dev.azure.com/mariner-org/mariner/_git/MarinerMos

**Comment by mjcheetham** [comment]
Hello, please can you capture trace logs and share them here?

```shell
$ GCM_TRACE=1 git push origin HEAD -v
```

**Comment by gjswalling** [comment]
I still don't get a pop-up windows, but after lunch started getting timeout error msgs:
$ git push origin HEAD -v
Pushing to https://dev.azure.com/mariner-org/mariner/_git/MarinerMos
fatal: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
fatal: A task was canceled.
fatal: A task was canceled.
Password for 'https://mariner-org@dev.azure.com/mariner-org/mariner/_git/MarinerMos': 
fatal: Authentication failed for 'https://dev.azure.com/mariner-org/mariner/_git/MarinerMos/'

And trace: 
$ GCM_TRACE=1 git push origin HEAD -v
Pushing to https://dev.azure.com/mariner-org/mariner/_git/MarinerMos
13:11:42.639275 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.0.0
13:11:42.644820 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.4
13:11:42.644872 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
13:11:42.644887 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.4 LTS
13:11:42.644921 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
13:11:42.645018 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
13:11:42.645052 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: get
13:11:42.674933 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'get' command...
13:11:42.701299 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
13:11:42.705882 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	protocol=https
13:11:42.706007 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	host=dev.azure.com
13:11:42.706048 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	path=mariner-org/mariner/_git/MarinerMos
13:11:42.706066 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	username=mariner-org
13:11:42.714393 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
13:11:42.718682 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
13:11:42.725587 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
13:11:42.726466 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
13:11:42.730335 ...sHostProvider.cs:476 trace: [UsePersonalAccessTokens] Azure Repos credential type override set to 'oauth'
13:11:42.733177 ...sHostProvider.cs:272 trace: [GetAzureAccessTokenAsync] Determining Microsoft Authentication authority for Azure DevOps organization 'mariner-org'...
13:11:42.743663 ...AuthorityCache.cs:57 trace: [GetAuthority] Looking up cached authority for organization 'mariner-org'...
13:11:42.770065 ...sHostProvider.cs:284 trace: [GetAzureAccessTokenAsync] No cached authority value - querying https://dev.azure.com/mariner-org for authority...
13:11:42.775184 ...eDevOpsRestApi.cs:43 trace: [GetAuthorityAsync] HTTP: HEAD https://dev.azure.com/mariner-org
13:11:42.779580 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
13:11:42.786097 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
fatal: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AzureRepos.AzureDevOpsRestApi.GetAuthorityAsync(Uri organizationUri)
   at Microsoft.AzureRepos.AzureReposHostProvider.GetAzureAccessTokenAsync(InputArguments input)
   at Microsoft.AzureRepos.AzureReposHostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
fatal: A task was canceled.

fatal: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Password for 'https://mariner-org@dev.azure.com/mariner-org/mariner/_git/MarinerMos': 
13:13:49.084049 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.0.0
13:13:49.089682 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.4
13:13:49.089714 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
13:13:49.089724 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.4 LTS
13:13:49.089734 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
13:13:49.089823 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
13:13:49.089855 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: erase
13:13:49.119210 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'erase' command...
13:13:49.141333 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
13:13:49.144897 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	protocol=https
13:13:49.145061 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	host=dev.azure.com
13:13:49.145104 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	path=mariner-org/mariner/_git/MarinerMos
13:13:49.145161 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	username=mariner-org
13:13:49.145304 ...GitCommandBase.cs:47 trace: [ExecuteAsync] 	password=********
13:13:49.152245 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
13:13:49.156636 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
13:13:49.162151 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
13:13:49.163081 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
13:13:49.165142 ...sHostProvider.cs:476 trace: [UsePersonalAccessTokens] Azure Repos credential type override set to 'oauth'
13:13:49.166127 ...sHostProvider.cs:195 trace: [EraseCredentialAsync] Signing out of organization 'mariner-org'...
13:13:49.166706 ...BindingManager.cs:94 trace: [GetBinding] Looking up organization binding for 'mariner-org'...
13:13:49.214445 ...indingManager.cs:123 trace: [Bind] Setting binding to 'do not inherit' for organization 'mariner-org' in local repository...
13:13:49.227293 ...AuthorityCache.cs:84 trace: [EraseAuthority] Removing cached authority for 'mariner-org'...
13:13:49.234338 ...GitCommandBase.cs:53 trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://dev.azure.com/mariner-org/mariner/_git/MarinerMos/'

**Comment by gjswalling** [comment]
why is username=mariner-org?

**Comment by mjcheetham** [comment]
> why is username=mariner-org?

Your remote URL is of the format `https://{org}@dev.azure.com/{org}`, so the first `{org}@` instance is where the username is being set. This can be ignored however. The issue seems to be network related:

```text
13:11:42.743663 ...AuthorityCache.cs:57 trace: [GetAuthority] Looking up cached authority for organization 'mariner-org'...
13:11:42.770065 ...sHostProvider.cs:284 trace: [GetAzureAccessTokenAsync] No cached authority value - querying https://dev.azure.com/mariner-org for authority...
13:11:42.775184 ...eDevOpsRestApi.cs:43 trace: [GetAuthorityAsync] HTTP: HEAD https://dev.azure.com/mariner-org
13:11:42.779580 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
13:11:42.786097 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
fatal: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

**Comment by gjswalling** [comment]
After fighting this most of the day (clone/push github worked but not ADO), I tried full poweroff (shutdown) and powered my PC back on.  This seemed to resolve the dotnet networking issue and I can push to my ADO repo again.
