### ISSUE TITLE
Failed to locate git.exe executable on path, windows 10 WSL2 without Git for Windows.

### ISSUE THREAD

**Issue by djmallum** [git-ecosystem/git-credential-manager#1692]
### Version

2.5.1+90d5f897f164a8fe07d2aa3bf7db439b0b4e03ea

### Operating system

Other - please describe below

### OS version or distribution

Ubuntu 22.04.3, WSL2

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

git push, into asking for my GCM password, into 'everything up to date'

### Actual behavior

`$ git push`

Error:

```
Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
   at GitCredentialManager.CommandContext..ctor()
   at GitCredentialManager.Program.AppMain(Object o)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```
   
Then it asks for my git username as if I had no credentials stored. Other git commands work fine as long as a password is not needed. My git.log trace is attached.

`git-credential-manager diagnose` was also successful. It is attached.

### Logs

git.log:

```
14:17:38.185631 git.c:455               trace: built-in: git status
14:17:39.593451 git.c:455               trace: built-in: git push
14:17:39.594123 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
14:17:39.599216 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:17:39.599440 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:17:40.071789 run-command.c:668       trace: run_command: '/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe get'
14:19:32.860672 git.c:455               trace: built-in: git config --null --list
14:19:32.931776 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.1.0
14:19:32.935499 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.6
14:19:32.935548 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
14:19:32.935556 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.3 LTS
14:19:32.935566 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
14:19:32.935692 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/bin/
14:19:32.935747 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: --version
14:21:30.153197 git.c:455               trace: built-in: git fetch
14:21:30.154167 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
14:21:30.159252 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:21:30.159408 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:21:30.704681 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
14:21:30.710415 git.c:455               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
14:21:30.723841 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
14:21:30.724031 run-command.c:1629      run_processes_parallel: done
14:21:30.724086 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
14:21:30.729623 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
14:21:36.096942 git.c:455               trace: built-in: git pull
14:21:36.098650 run-command.c:668       trace: run_command: git fetch --update-head-ok
14:21:36.110255 git.c:455               trace: built-in: git fetch --update-head-ok
14:21:36.112714 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
14:21:36.117838 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:21:36.117976 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
14:21:36.613651 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
14:21:36.619083 git.c:455               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
14:21:36.633021 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
14:21:36.633131 run-command.c:1629      run_processes_parallel: done
14:21:36.633180 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
14:21:36.638622 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
14:21:36.642631 run-command.c:668       trace: run_command: git merge FETCH_HEAD
14:21:36.648038 git.c:455               trace: built-in: git merge FETCH_HEAD
14:23:07.926096 git.c:455               trace: built-in: git config --null --list
14:23:07.976910 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.1.0
14:23:07.980399 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.6
14:23:07.980442 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
14:23:07.980470 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.3 LTS
14:23:07.980480 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
14:23:07.980551 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/bin/
14:23:07.980579 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: diagnose
14:23:08.034526 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
14:23:08.040759 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
14:23:08.835604 ...edentialStore.cs:364 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
14:23:09.715227 ...GitHubRestApi.cs:118 trace: [GetMetaInfoAsync] HTTP: GET https://api.github.com/meta
14:23:09.715479 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
14:23:09.715536 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
14:23:10.300340 ...GitHubRestApi.cs:122 trace: [GetMetaInfoAsync] HTTP: Response 200 [OK]
lt-in: git config --null --type=path http.sslCAInfo
14:23:09.718775 git.c:455               trace: built-in: git config --null --type=path http.cookieFile
```

gcm-diagnose.log:

```
Diagnose log at 2024-08-20T20:23:08Z

AppPath: /usr/local/bin/git-credential-manager
InstallDir: /usr/local/bin/
Version: 2.5.1+90d5f897f164a8fe07d2aa3bf7db439b0b4e03ea

------------
Diagnostic: Environment
Skipped: False
Success: True
Exception: None
Log:
OSType: Linux
OSVersion: Ubuntu 22.04.3 LTS
Reading environment variables... OK
 Variables:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/e/Program Files/MATLAB/R2020a/bin:/mnt/e/Program Files/dotnet/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/e/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/The Kid Part 2/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/The Kid Part 2/AppData/Local/Programs/MiKTeX/miktex/bin/x64/:/snap/bin
USER=XXXXX
_=/usr/local/bin/git-credential-manager
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
WAYLAND_DISPLAY=wayland-0
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
OLDPWD=XXXXX
WSLENV=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
WSL_INTEROP=/run/WSL/18497_interop
WSL2_GUI_APPS_ENABLED=1
WSL_DISTRO_NAME=Ubuntu
LOGNAME=XXXXX
LESSOPEN=| /usr/bin/lesspipe %s
HOSTTYPE=x86_64
LANG=C.UTF-8
SHLVL=1
GIT_TRACE=XXXXX
TERM=xterm-256color
SHELL=/bin/bash
DISPLAY=:0
PWD=XXXXX
GCM_TRACE=XXXXX
LESSCLOSE=/usr/bin/lesspipe %s %s
HOME=XXXXX
PULSE_SERVER=unix:/mnt/wslg/PulseServer
NAME=XXXXX
GIT_TRACE2_PARENT_SID=09d4f134-baac-48e5-a87f-51e18840ede2
XDG_RUNTIME_DIR=/run/user/1000/


------------
Diagnostic: File system
Skipped: False
Success: True
Exception: None
Log:
Temporary directory is '/tmp/'...
Checking basic file I/O...
Writing to temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
Reading from temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
Deleting temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
Testing IFileSystem instance...
UserHomePath: XXXXX
UserDataDirectoryPath: XXXXX/.gcm
GetCurrentDirectory(): XXXXX

------------
Diagnostic: Networking
Skipped: False
Success: True
Exception: None
Log:
Checking networking and HTTP stack...
Creating HTTP client... OK
IsNetworkAvailable: True
Sending HEAD request to http://example.com...Sending HEAD request to https://example.com... OK
 OK
Acquiring free TCP port... OK
Testing local HTTP loopback connections...
Creating new HTTP listener for XXXXX... OK
Waiting for loopback connection... OK
Writing response... OK
Waiting for response data... OK
Loopback connection data OK

------------
Diagnostic: Git
Skipped: False
Success: True
Exception: None
Log:
Getting Git version... OK
Git version is '2.34.1'
Locating current repository...Not inside a Git repository.
 OK
Listing all Git configuration... OK
Git configuration:
file:/home/dallum/.gitconfig	credential.credentialstore=gpg
file:/home/dallum/.gitconfig	credential.guiprompt=false
file:/home/dallum/.gitconfig	credential.helper=/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe
file:/home/dallum/.gitconfig	credential.https://dev.azure.com.usehttppath=true
file:/home/dallum/.gitconfig	user.name=XXXXX
file:/home/dallum/.gitconfig	user.email=XXXXX
file:/home/dallum/.gitconfig	gpg.program=/usr/bin/gpg
file:/home/dallum/.gitconfig	core.excludesfile=XXXXX/.gitignore_global


------------
Diagnostic: Credential storage
Skipped: False
Success: True
Exception: None
Log:
ICredentialStore instance is of type: CredentialStore
Writing test credential... OK
Reading test credential... OK
Deleting test credential... OK

------------
Diagnostic: Microsoft authentication (AAD/MSA)
Skipped: False
Success: True
Exception: None
Log:
Broker is not enabled.
Flow type is: Auto
Gathering MSAL token cache data... OK
CacheDirectory: XXXXX/.local/.IdentityService
CacheFileName: msal.cache
CacheFilePath: XXXXX/.local/.IdentityService/msal.cache
KeyringCollection: 
KeyringSchemaName: 
KeyringSecretLabel: 
KeyringAttribute1: (,)
KeyringAttribute2: (,)
Creating cache helper... OK
Verifying MSAL token cache persistence... OK

------------
Diagnostic: GitHub API
Skipped: False
Success: True
Exception: None
Log:
Using 'https://github.com/' as API target.
Querying '/meta' endpoint... OK`
```

**Comment by Bowo78** [comment]
> ### Versi
> 2.5.1+90d5f897f164a8fe07d2aa3bf7db439b0b4e03ea
> 
> ### Sistem operasi
> Lainnya - harap jelaskan di bawah ini
> 
> ### Versi atau distribusi OS
> Ubuntu 22.04.3, WSL2
> 
> ### Penyedia hosting Git
> Bahasa Indonesia: GitHub
> 
> ### Penyedia hosting lainnya
> _Tidak ada respon_
> 
> ### (Khusus Azure DevOps) Apa format URL jarak jauh Anda?
> Tidak ada
> 
> ### Dapatkah Anda mengakses repositori jarak jauh langsung di peramban?
> Ya, saya dapat mengakses repositori
> 
> ### Perilaku yang diharapkan
> git push, ke dalam permintaan kata sandi GCM saya, ke dalam 'semuanya terkini'
> 
> ### Perilaku sebenarnya
> `$ git push`
> 
> Kesalahan:
> 
> ```
> Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
>    at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
>    at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
>    at GitCredentialManager.CommandContext..ctor()
>    at GitCredentialManager.Program.AppMain(Object o)
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)
> ```
> 
> Kemudian ia meminta nama pengguna git saya seolah-olah saya tidak menyimpan kredensial apa pun. Perintah git lainnya berfungsi dengan baik selama kata sandi tidak diperlukan. Jejak git.log saya terlampir.
> 
> `git-credential-manager diagnose`juga berhasil. Terlampir.
> 
> ### Catatan
> catatan git:
> 
> ```
> 14:17:38.185631 git.c:455               trace: built-in: git status
> 14:17:39.593451 git.c:455               trace: built-in: git push
> 14:17:39.594123 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
> 14:17:39.599216 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:17:39.599440 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:17:40.071789 run-command.c:668       trace: run_command: '/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe get'
> 14:19:32.860672 git.c:455               trace: built-in: git config --null --list
> 14:19:32.931776 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.1.0
> 14:19:32.935499 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.6
> 14:19:32.935548 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
> 14:19:32.935556 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.3 LTS
> 14:19:32.935566 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
> 14:19:32.935692 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/bin/
> 14:19:32.935747 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: --version
> 14:21:30.153197 git.c:455               trace: built-in: git fetch
> 14:21:30.154167 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:30.159252 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:30.159408 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:30.704681 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
> 14:21:30.710415 git.c:455               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
> 14:21:30.723841 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
> 14:21:30.724031 run-command.c:1629      run_processes_parallel: done
> 14:21:30.724086 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
> 14:21:30.729623 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
> 14:21:36.096942 git.c:455               trace: built-in: git pull
> 14:21:36.098650 run-command.c:668       trace: run_command: git fetch --update-head-ok
> 14:21:36.110255 git.c:455               trace: built-in: git fetch --update-head-ok
> 14:21:36.112714 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:36.117838 git.c:742               trace: exec: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:36.117976 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/djmallum/crhmcode.git
> 14:21:36.613651 run-command.c:668       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
> 14:21:36.619083 git.c:455               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
> 14:21:36.633021 run-command.c:1597      run_processes_parallel: preparing to run up to 1 tasks
> 14:21:36.633131 run-command.c:1629      run_processes_parallel: done
> 14:21:36.633180 run-command.c:668       trace: run_command: git maintenance run --auto --no-quiet
> 14:21:36.638622 git.c:455               trace: built-in: git maintenance run --auto --no-quiet
> 14:21:36.642631 run-command.c:668       trace: run_command: git merge FETCH_HEAD
> 14:21:36.648038 git.c:455               trace: built-in: git merge FETCH_HEAD
> 14:23:07.926096 git.c:455               trace: built-in: git config --null --list
> 14:23:07.976910 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.1.0
> 14:23:07.980399 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.6
> 14:23:07.980442 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: Linux (x86-64)
> 14:23:07.980470 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: Ubuntu 22.04.3 LTS
> 14:23:07.980480 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
> 14:23:07.980551 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/bin/
> 14:23:07.980579 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: diagnose
> 14:23:08.034526 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
> 14:23:08.040759 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
> 14:23:08.835604 ...edentialStore.cs:364 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
> 14:23:09.715227 ...GitHubRestApi.cs:118 trace: [GetMetaInfoAsync] HTTP: GET https://api.github.com/meta
> 14:23:09.715479 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
> 14:23:09.715536 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
> 14:23:10.300340 ...GitHubRestApi.cs:122 trace: [GetMetaInfoAsync] HTTP: Response 200 [OK]
> lt-in: git config --null --type=path http.sslCAInfo
> 14:23:09.718775 git.c:455               trace: built-in: git config --null --type=path http.cookieFile
> ```
> 
> gcm-diagnose.log:
> 
> ```
> Diagnose log at 2024-08-20T20:23:08Z
> 
> AppPath: /usr/local/bin/git-credential-manager
> InstallDir: /usr/local/bin/
> Version: 2.5.1+90d5f897f164a8fe07d2aa3bf7db439b0b4e03ea
> 
> ------------
> Diagnostic: Environment
> Skipped: False
> Success: True
> Exception: None
> Log:
> OSType: Linux
> OSVersion: Ubuntu 22.04.3 LTS
> Reading environment variables... OK
>  Variables:
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/e/Program Files/MATLAB/R2020a/bin:/mnt/e/Program Files/dotnet/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/e/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/The Kid Part 2/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/The Kid Part 2/AppData/Local/Programs/MiKTeX/miktex/bin/x64/:/snap/bin
> USER=XXXXX
> _=/usr/local/bin/git-credential-manager
> LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
> WAYLAND_DISPLAY=wayland-0
> XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
> OLDPWD=XXXXX
> WSLENV=
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> WSL_INTEROP=/run/WSL/18497_interop
> WSL2_GUI_APPS_ENABLED=1
> WSL_DISTRO_NAME=Ubuntu
> LOGNAME=XXXXX
> LESSOPEN=| /usr/bin/lesspipe %s
> HOSTTYPE=x86_64
> LANG=C.UTF-8
> SHLVL=1
> GIT_TRACE=XXXXX
> TERM=xterm-256color
> SHELL=/bin/bash
> DISPLAY=:0
> PWD=XXXXX
> GCM_TRACE=XXXXX
> LESSCLOSE=/usr/bin/lesspipe %s %s
> HOME=XXXXX
> PULSE_SERVER=unix:/mnt/wslg/PulseServer
> NAME=XXXXX
> GIT_TRACE2_PARENT_SID=09d4f134-baac-48e5-a87f-51e18840ede2
> XDG_RUNTIME_DIR=/run/user/1000/
> 
> 
> ------------
> Diagnostic: File system
> Skipped: False
> Success: True
> Exception: None
> Log:
> Temporary directory is '/tmp/'...
> Checking basic file I/O...
> Writing to temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
> Reading from temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
> Deleting temporary file '/tmp/a8b94316bac13b3f5b1a6e5a'... OK
> Testing IFileSystem instance...
> UserHomePath: XXXXX
> UserDataDirectoryPath: XXXXX/.gcm
> GetCurrentDirectory(): XXXXX
> 
> ------------
> Diagnostic: Networking
> Skipped: False
> Success: True
> Exception: None
> Log:
> Checking networking and HTTP stack...
> Creating HTTP client... OK
> IsNetworkAvailable: True
> Sending HEAD request to http://example.com...Sending HEAD request to https://example.com... OK
>  OK
> Acquiring free TCP port... OK
> Testing local HTTP loopback connections...
> Creating new HTTP listener for XXXXX... OK
> Waiting for loopback connection... OK
> Writing response... OK
> Waiting for response data... OK
> Loopback connection data OK
> 
> ------------
> Diagnostic: Git
> Skipped: False
> Success: True
> Exception: None
> Log:
> Getting Git version... OK
> Git version is '2.34.1'
> Locating current repository...Not inside a Git repository.
>  OK
> Listing all Git configuration... OK
> Git configuration:
> file:/home/dallum/.gitconfig	credential.credentialstore=gpg
> file:/home/dallum/.gitconfig	credential.guiprompt=false
> file:/home/dallum/.gitconfig	credential.helper=/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager/git-credential-manager.exe
> file:/home/dallum/.gitconfig	credential.https://dev.azure.com.usehttppath=true
> file:/home/dallum/.gitconfig	user.name=XXXXX
> file:/home/dallum/.gitconfig	user.email=XXXXX
> file:/home/dallum/.gitconfig	gpg.program=/usr/bin/gpg
> file:/home/dallum/.gitconfig	core.excludesfile=XXXXX/.gitignore_global
> 
> 
> ------------
> Diagnostic: Credential storage
> Skipped: False
> Success: True
> Exception: None
> Log:
> ICredentialStore instance is of type: CredentialStore
> Writing test credential... OK
> Reading test credential... OK
> Deleting test credential... OK
> 
> ------------
> Diagnostic: Microsoft authentication (AAD/MSA)
> Skipped: False
> Success: True
> Exception: None
> Log:
> Broker is not enabled.
> Flow type is: Auto
> Gathering MSAL token cache data... OK
> CacheDirectory: XXXXX/.local/.IdentityService
> CacheFileName: msal.cache
> CacheFilePath: XXXXX/.local/.IdentityService/msal.cache
> KeyringCollection: 
> KeyringSchemaName: 
> KeyringSecretLabel: 
> KeyringAttribute1: (,)
> KeyringAttribute2: (,)
> Creating cache helper... OK
> Verifying MSAL token cache persistence... OK
> 
> ------------
> Diagnostic: GitHub API
> Skipped: False
> Success: True
> Exception: None
> Log:
> Using 'https://github.com/' as API target.
> Querying '/meta' endpoint... OK`
> ```

No

**Comment by Bowo78** [comment]
No SLJJ

**Comment by djmallum** [comment]
Hi Thanks for checking this out. I will close this issue because I've moved on from WSL to dual boot. I'll reopen if I start having similar issues in the future.
