### ISSUE TITLE
git-credential-manager as .NET tool still .NET 7.0?

### ISSUE THREAD

**Issue by BruceForstall** [git-ecosystem/git-credential-manager#1702]
### Feature description

It appears that the .NET global tool version of git-credential-manager is version 2.4.1, and still dependent on the out-of-support .NET 7.0 (https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md#net-tool).

Will it be updated to the latest, and be based on .NET 8.0 (LTS) soon?

**Comment by xtqqczze** [comment]
> We are currently facing some issues publishing a correctly signed package to Nuget.org. Due to recent sponsorship/corporate funding priority changes, work on GCM has unfortunately slowed significantly.
> 
> Please watch this space!

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/issues/1606#issuecomment-2150748156_

**Comment by mjcheetham** [comment]
GCM 2.6 which targets .NET 8 has just been released on nuget.org

https://www.nuget.org/packages/git-credential-manager/2.6.0
