### ISSUE TITLE
Do not recommend dotnet installation for Linux

### ISSUE THREAD

**Issue by NVolcz** [git-ecosystem/git-credential-manager#1703]
The [current installation instructions for linux](https://github.com/git-ecosystem/git-credential-manager/blob/90d5f897f164a8fe07d2aa3bf7db439b0b4e03ea/docs/install.md?plain=1#L64-L69) recommends to install GCM through the .Net tool. This will sadly cause Linux users to use the EOL .Net version 7.0, while to my understanding the other installation options support .Net 8.0 since [GCM version 2.5](https://github.com/git-ecosystem/git-credential-manager/pull/1587).

Is there any reason for recommending this? Should the docs be updated?

**Comment by xtqqczze** [comment]
> We are currently facing some issues publishing a correctly signed package to Nuget.org. Due to recent sponsorship/corporate funding priority changes, work on GCM has unfortunately slowed significantly.
> 
> Please watch this space!

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/issues/1606#issuecomment-2150748156_

**Comment by xtqqczze** [comment]
> GCM 2.6 which targets .NET 8 has just been released on nuget.org
> 
> https://www.nuget.org/packages/git-credential-manager/2.6.0

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/issues/1702#issuecomment-2383279743_

**Comment by Scutua** [comment]
please check
