### ISSUE TITLE
GCM 2.6.0 is marked as prerelease on GitHub but not NuGet

### ISSUE THREAD

**Issue by xtqqczze** [git-ecosystem/git-credential-manager#1716]
cc: @mjcheetham

**Comment by xtqqczze** [comment]
Version 2.6.0 of the Homebrew [`git-credential-manager` cask](https://formulae.brew.sh/cask/git-credential-manager) is blocked, as the GitHub release is marked as prerelease.

**Comment by mjcheetham** [comment]
2.6 should now be marked as a full release on GitHub.
