### ISSUE TITLE
Certificate validation failed

### ISSUE THREAD

**Issue by enya-yx** [git-ecosystem/git-credential-manager#1758]
### Version

2.6.0+3c28096588f549cb46f36b552390514356830abe

### Operating system

Windows

### OS version or distribution

Windows 11 Enterprise, x64

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Should have write access to repos in Azure DevOps when 'git clone', 'git pull'. It worked well previously

### Actual behavior

Got below error when trying 'git pull' for all repos:
![image](https://github.com/user-attachments/assets/29d5df6d-583f-46c0-8acc-3af4f898bc3c)

**Comment by dscho** [comment]
Could you re-run with `GCM_TRACE` set and then study the log whether it contains any hint about what is going on?

**Comment by enya-yx** [comment]
@dscho , thanks helping check. I rerun 'git pull' and got below trace log. 
[trace.log](https://github.com/user-attachments/files/17672147/trace.log)

More details are after warnings: 'warning: iCCP: known incorrect sRGB profile', I got the pump to select account. 
![select account](https://github.com/user-attachments/assets/6431a609-9b04-4fb8-8b3c-c546190fd57e)

When I selected myself, got the 'Certificate validation failed' error. Then I just close the window and then it showed 'fatal: User canceled authentication.'

**Comment by enya-yx** [comment]
@dscho, could you help provide suggestion? I need to submit a PR and got blocked by this issue. Thx

**Comment by dscho** [comment]
@enya-yx I am stabbing in the dark, just like you.

Seeing this line:

```
11:09:20.683918 ...uthentication.cs:137 trace: [GetTokenForUserAsync] OS broker is not available or enabled.
```

makes me suspect that you may want to try setting [`credential.msauthUseBroker=true`](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/configuration.md#credentialmsauthusebroker-experimental). Also, since I see this line:

```
11:09:20.774448 ...uthentication.cs:230 trace: [GetTokenForUserAsync] Performing interactive auth with embedded web view...
```

it might be worth experimenting with [`credential.msauthFlow=system`](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/configuration.md#credentialmsauthflow).

**Comment by enya-yx** [comment]
@dscho, that works. Thanks a lot.

**Comment by dscho** [comment]
> that works.

@enya-yx I am curious which of the two suggestions worked. In any case, seems you are unblocked, so I'll close this ticket.

**Comment by ravikr-dev** [comment]
this worked for me [credential.msauthUseBroker=true](https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/configuration.md#credentialmsauthusebroker-experimental)
