### ISSUE TITLE
XOpenDisplay failed when logged in via ssh

### ISSUE THREAD

**Issue by ghost** [git-ecosystem/git-credential-manager#1762]
### Version

2.6.0+3c28096588f549cb46f36b552390514356830abe

### Operating system

Linux

### OS version or distribution

ubuntu 22.04

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

show a url and user map the port to login

### Actual behavior

XOpenDisplay failed when logged in via ssh

### Logs
```
Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithoutStarting()
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass8_1.<ShowWindowAsync>b__1(CancellationToken appCancelToken)
   at GitCredentialManager.UI.Dispatcher.DispatcherJob.Execute(CancellationToken ct)
   at GitCredentialManager.UI.Dispatcher.DispatcherJobQueue.Run()
   at GitCredentialManager.UI.Dispatcher.Run()
   at GitCredentialManager.Program.Main(String[] args)
Aborted (core dumped)
remote: Repository not found.
```

**Comment by dscho** [comment]
Umm. Did you use [X11 Forwarding](https://ostechnix.com/how-to-configure-x11-forwarding-using-ssh-in-linux/)? If not, this error is totally expected.

**Comment by dscho** [comment]
@write3371 have you played around with [`GCM_GUI_PROMPT`](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/environment.md#gcm_gui_prompt) yet?

**Comment by dscho** [comment]
> yes, it tried

And? What did happen?

> but it still does not show the url, if i try to use any site other than github (say, gitea)

It may not be as easy as showing a URL in all cases, unless you enable something like a Device Token flow.

**Comment by dscho** [comment]
> does gitea support Device Token flow?

I don't know?

**Comment by cboettig** [comment]
> Umm. Did you use [X11 Forwarding](https://ostechnix.com/how-to-configure-x11-forwarding-using-ssh-in-linux/)? If not, this error is totally expected.

Wouldn't it make more sense for git-credential-manager to automatically fallback on the --no-ui behavior in this situation?  It's not clear why a core dump should be the expected / desired behavior for the software under these circumstances.
