### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by ghost** [git-ecosystem/git-credential-manager#907]

**Comment by mjcheetham** [comment]
@uranuspucksaxophone please can you try running the following command inside of your repository, and share the resulting log file (please redact any sensitive information!):

```sh
git credential-manager-core diagnose
```

Can I also ask what the start of your remote URL looks like? Does it include a specific port number?

```shellsession
$ git remote -vv
origin	https://github.com:1234/example/repo (fetch)
origin	https://github.com:1234/example/repo (push)
```

**Comment by ldennington** [comment]
Can you please do the following:

1. Download [dotnet](https://learn.microsoft.com/en-us/dotnet/core/install/linux).
2. Create the following files in a directory you choose:

Test.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
```

Program.cs
```
var httpClient = new HttpClient();
var response = await httpClient.GetAsync("http://example.com/");
var body = await response.Content.ReadAsStringAsync();
Console.WriteLine(body);
```
3. Navigate to the directory and run `dotnet run`

The example.com page should be printed to your terminal. If it is not, this is a dotnet issue with Whonix and should be re-directed to the [dotnet team](https://github.com/dotnet/runtime) for investigation.
