### ISSUE TITLE
Improve support for running in Codespaces

### ISSUE THREAD

**Issue by markphip** [git-ecosystem/git-credential-manager#945]
**Feature description**
GCM sort of works if run in Codespaces (with Azure DevOps). First off, it uses `devicecode` flow. This works fine if you use git from the VS Code Terminal. Once you do this, as long as you have some kind of caching enabled, the VS Code GUI will also work.

If you start in the VS Code GUI then it does not work. GCM sends the device code information to `/dev/tty` but VS Code is not trying to capture this or show it to the user so it is not possible to see the output. I modified the GCM code to output to `stderr` instead and this almost works. This output does get captured by VS Code and displayed in their Git Output window. However, it does not output anything until the command fails. I glanced at the VS Code source code and it seems like it always runs Git operations in a try/catch so while it does capture stderr it does not look at the output until the operation completes.

Shifting gears, I tried another approach. In GCM, I added a quick hack to also write `dcr.Message` to a text file in `$HOME/.somedir`. I then used a VS Code extension to monitor this folder and when the text file arrives it displays the information to the user ins VS Code. I think a better option would be to serialize the entire dcr object to JSON so that the receiver would have more flexibility in how it displays the URL and Code to the user.

What I am asking for? Could be one of a number of approaches:

1. Let me register a helper script with GCM that is called for the DeviceCode flow. This would pass me the JSON object and then it would be up to me to implement some kind of solution that would relay the information to the VS Code UI. Perhaps using a variant of my hack, perhaps something better.
2. Another option might be to just have a setting that tells GCM to output a text file like I did in my hack. The helper script approach seems better as worst case a simple bash script could create this text file but maybe a better option could be found.
3. You should investigate whether you should be writing to `stderr` instead of `/dev/tty`. Maybe there is at least a way to recognize if nothing is attached to `tty` and then use `stderr`? It is unclear if VS Code will ever handle any of this better but this would at least give it a chance. Using `stderr` seemed to work fine.

**Comment by ldennington** [comment]
Closing - requestor has switched to a different solution that better meets their customers' needs.
